import type { Drill, Level } from '../types';
import { hash } from '../engine/random';

/** Gap drill: [level, rule, sentence with ___, answer, wrong options, translation, extra]. */
type GapRow = [Level, string, string, string, string[], string, Partial<Drill>?];
/** "Which sentence is correct?": [level, rule, correct sentence, wrong sentences, translation]. */
type FixRow = [Level, string, string, string[], string];

const NONE = '—';

const GAPS: GapRow[] = [
  ['B1', 'prep-time', 'The meeting starts ___ 9 o’clock.', 'at', ['in', 'on'], 'Совещание начинается в 9 часов.'],
  ['B1', 'prep-time', 'My birthday is ___ June.', 'in', ['on', 'at'], 'Мой день рождения в июне.'],
  ['B1', 'prep-time', 'See you ___ Friday!', 'on', ['in', 'at'], 'Увидимся в пятницу!'],
  ['B1', 'prep-time', 'I usually read ___ the evening.', 'in', ['at', 'on'], 'Я обычно читаю по вечерам.'],
  ['B1', 'prep-time', 'The shop is closed ___ night.', 'at', ['in', 'on'], 'Ночью магазин закрыт.'],
  ['B1', 'prep-place', 'Let’s meet ___ the bus stop.', 'at', ['in', 'on'], 'Давай встретимся на автобусной остановке.'],
  ['B1', 'prep-place', 'She’s still ___ work.', 'at', ['in', 'on'], 'Она всё ещё на работе.'],
  ['B1', 'prep-place', 'There’s a picture ___ the wall.', 'on', ['in', 'at'], 'На стене висит картина.'],
  ['B1', 'prep-place', 'We arrived ___ London late at night.', 'in', ['to', 'at'], 'Мы приехали в Лондон поздно ночью.'],
  ['B1', 'prep-place', 'The bank is ___ the left.', 'on', ['in', 'at'], 'Банк слева.'],
  ['B1', 'articles', 'My sister is ___ nurse.', 'a', ['the', NONE], 'Моя сестра — медсестра.', { typeable: false }],
  ['B1', 'articles', 'I waited for ___ hour.', 'an', ['a', 'the'], 'Я ждал целый час.', { typeable: false }],
  ['B1', 'articles', '___ sun rises in the east.', 'The', ['A', NONE], 'Солнце встаёт на востоке.', { typeable: false }],
  ['B1', 'articles', '___ life is too short to worry.', NONE, ['The', 'A'], 'Жизнь слишком коротка, чтобы переживать.', { typeable: false }],
  ['B1', 'present-perfect', 'I ___ that film last week.', 'saw', ['have seen', 'had seen'], 'Я посмотрел этот фильм на прошлой неделе.'],
  ['B1', 'present-perfect', 'Have you ever ___ sushi?', 'eaten', ['ate', 'eat'], 'Ты когда-нибудь ел суши?'],
  ['B1', 'present-perfect', 'They ___ married in 2015.', 'got', ['have got', 'have been got'], 'Они поженились в 2015 году.'],
  ['B1', 'present-perfect', 'I ___ here since 2018.', 'have lived', ['live', 'am living', 'lived'], 'Я живу здесь с 2018 года.', { alt: ['’ve lived', 'have been living'] }],
  ['B1', 'for-since', 'I’ve worked here ___ three years.', 'for', ['since', 'during'], 'Я работаю здесь уже три года.'],
  ['B1', 'for-since', 'We’ve been friends ___ school.', 'since', ['for', 'from'], 'Мы дружим со школы.'],
  ['B1', 'for-since', 'She has lived in Paris ___ 2019.', 'since', ['for', 'from'], 'Она живёт в Париже с 2019 года.'],
  ['B1', 'make-do', 'Everyone ___ mistakes sometimes.', 'makes', ['does', 'takes'], 'Все иногда ошибаются.'],
  ['B1', 'make-do', 'Could you ___ me a favour?', 'do', ['make', 'give'], 'Можешь сделать мне одолжение?'],
  ['B1', 'make-do', 'I need to ___ a decision today.', 'make', ['do', 'have'], 'Мне нужно принять решение сегодня.'],
  ['B1', 'make-do', 'Who ___ the washing-up yesterday?', 'did', ['made', 'has made'], 'Кто вчера мыл посуду?'],
  ['B1', 'make-do', 'I try to ___ exercise every morning.', 'do', ['make', 'play'], 'Я стараюсь делать зарядку каждое утро.'],
  ['B1', 'verb-patterns', 'I enjoy ___ in the mountains.', 'walking', ['to walk', 'walk'], 'Я люблю гулять в горах.'],
  ['B1', 'verb-patterns', 'We’ve decided ___ a new car.', 'to buy', ['buying', 'buy'], 'Мы решили купить новую машину.'],
  ['B1', 'verb-patterns', 'Would you mind ___ the window?', 'opening', ['to open', 'open'], 'Не могли бы вы открыть окно?'],
  ['B1', 'verb-patterns', 'He managed ___ the exam.', 'to pass', ['passing', 'pass'], 'Ему удалось сдать экзамен.'],
  ['B1', 'verb-patterns', 'She suggested ___ a taxi.', 'taking', ['to take', 'take'], 'Она предложила взять такси.'],
  ['B1', 'verb-patterns', 'I can’t afford ___ a new car.', 'to buy', ['buying', 'buy'], 'Я не могу позволить себе купить новую машину.'],
  ['B2', 'verb-patterns', 'The museum is worth ___.', 'visiting', ['to visit', 'visit'], 'Этот музей стоит посетить.'],
  ['B2', 'verb-patterns', 'He denied ___ the window.', 'breaking', ['to break', 'break'], 'Он отрицал, что разбил окно.'],
  ['B2', 'verb-patterns', 'Have you considered ___ abroad?', 'studying', ['to study', 'study'], 'Ты не думал учиться за границей?'],
  ['B1', 'to-preposition', 'I look forward to ___ from you.', 'hearing', ['hear', 'heard'], 'Жду вашего ответа.'],
  ['B1', 'to-preposition', 'I’m not used to ___ so early.', 'getting up', ['get up', 'got up'], 'Я не привык вставать так рано.'],
  ['B2', 'used-to', 'I ___ play tennis when I was a child.', 'used to', ['use to', 'was used to'], 'В детстве я играл в теннис.'],
  ['B2', 'used-to', 'Don’t worry, you’ll soon get used to ___ on the left.', 'driving', ['drive', 'drove'], 'Не волнуйся, скоро привыкнешь ездить по левой стороне.'],
  ['B2', 'used-to', 'Did you ___ live in the countryside?', 'use to', ['used to', 'using to'], 'Ты раньше жил за городом?'],
  ['B1', 'dep-prep', 'It depends ___ the weather.', 'on', ['of', 'from'], 'Это зависит от погоды.'],
  ['B1', 'dep-prep', 'She’s very good ___ maths.', 'at', ['in', 'on'], 'Она очень хорошо разбирается в математике.'],
  ['B1', 'dep-prep', 'I’m interested ___ photography.', 'in', ['at', 'about'], 'Я интересуюсь фотографией.'],
  ['B1', 'dep-prep', 'We’re waiting ___ the bus.', 'for', [NONE, 'to'], 'Мы ждём автобус.'],
  ['B1', 'dep-prep', 'Are you afraid ___ spiders?', 'of', ['from', 'about'], 'Ты боишься пауков?'],
  ['B1', 'dep-prep', 'Please listen ___ me!', 'to', [NONE, 'at'], 'Пожалуйста, послушай меня!'],
  ['B2', 'dep-prep', 'He insisted ___ paying for dinner.', 'on', ['in', 'to'], 'Он настоял на том, чтобы заплатить за ужин.'],
  ['B2', 'dep-prep', 'You can always rely ___ me.', 'on', ['in', 'at'], 'Ты всегда можешь на меня положиться.'],
  ['B2', 'dep-prep', 'She’s responsible ___ marketing.', 'for', ['of', 'about'], 'Она отвечает за маркетинг.'],
  ['B1', 'agree', 'I ___ with you completely.', 'agree', ['am agree', 'am agreed'], 'Я полностью с тобой согласен.'],
  ['B1', 'say-tell', 'Can you ___ me the way to the station?', 'tell', ['say', 'explain'], 'Можете подсказать дорогу до вокзала?'],
  ['B1', 'say-tell', 'She ___ that she was tired.', 'said', ['told', 'spoke'], 'Она сказала, что устала.'],
  ['B1', 'say-tell', 'Could you explain the rule ___ me?', 'to', [NONE, 'for'], 'Не могли бы вы объяснить мне правило?'],
  ['B1', 'say-tell', 'He didn’t ___ me the truth.', 'tell', ['say', 'speak'], 'Он не сказал мне правду.'],
  ['B1', 'false-friends', 'I bought a fashion ___ to read on the train.', 'magazine', ['shop', 'store'], 'Я купил модный журнал, чтобы почитать в поезде.'],
  ['B2', 'false-friends', 'Is this information still ___?', 'relevant', ['actual', 'accurate'], 'Эта информация всё ещё актуальна?'],
  ['B2', 'false-friends', 'He was very ___ when I told him about my problem.', 'sympathetic', ['sympathic', 'sensible'], 'Он очень мне посочувствовал, когда я рассказал о своей проблеме.'],
  ['B1', 'false-friends', 'My father worked at a car ___ for 30 years.', 'factory', ['fabric', 'fabrique'], 'Мой отец 30 лет проработал на автомобильном заводе.'],
  ['B2', 'false-friends', 'The report must be ___: check every number.', 'accurate', ['actual', 'sensible'], 'Отчёт должен быть точным: проверь каждую цифру.'],
  ['B1', 'countable', 'Can I give you some ___?', 'advice', ['advices', 'an advice'], 'Можно дать тебе совет?'],
  ['B1', 'countable', 'The news ___ good.', 'is', ['are', 'were'], 'Новости хорошие.'],
  ['B1', 'countable', 'How ___ luggage have you got?', 'much', ['many', 'lot of'], 'Сколько у тебя багажа?'],
  ['B1', 'countable', 'I need ___ information about the course.', 'some', ['an', 'many'], 'Мне нужна информация о курсе.'],
  ['B1', 'conditionals', 'If it ___ tomorrow, we’ll stay at home.', 'rains', ['will rain', 'would rain'], 'Если завтра будет дождь, мы останемся дома.'],
  ['B1', 'conditionals', 'If I ___ more time, I would learn Spanish.', 'had', ['have', 'would have'], 'Если бы у меня было больше времени, я бы выучил испанский.'],
  ['B1', 'conditionals', 'If I ___ you, I’d apologise.', 'were', ['am', 'would be'], 'На твоём месте я бы извинился.', { alt: ['was'] }],
  ['B2', 'conditionals', 'If I had known, I ___ you.', 'would have told', ['would tell', 'will tell'], 'Если бы я знал, я бы тебе сказал.', { alt: ['’d have told'] }],
  ['B1', 'ed-ing', 'The film was so ___ that I fell asleep.', 'boring', ['bored'], 'Фильм был таким скучным, что я уснул.'],
  ['B1', 'ed-ing', 'I’m really ___ in modern art.', 'interested', ['interesting'], 'Мне очень интересно современное искусство.'],
  ['B1', 'ed-ing', 'It was an ___ day. I need to rest.', 'exhausting', ['exhausted'], 'Это был изматывающий день. Мне нужно отдохнуть.'],
  ['B1', 'ed-ing', 'We were ___ by the news.', 'surprised', ['surprising'], 'Новость нас удивила.'],
  ['B2', 'modals', 'You ___ smoke in the hospital. It’s forbidden.', 'mustn’t', ['don’t have to', 'needn’t'], 'В больнице курить нельзя. Это запрещено.', { alt: ['must not'] }],
  ['B2', 'modals', 'You ___ bring anything. We have everything.', 'don’t have to', ['mustn’t', 'can’t'], 'Можешь ничего не приносить. У нас всё есть.', { alt: ['do not have to', 'don’t need to', 'needn’t'] }],
  ['B2', 'modals', 'Yesterday I ___ wait two hours for the doctor.', 'had to', ['must', 'musted'], 'Вчера мне пришлось ждать врача два часа.'],
  ['B2', 'wish', 'I wish I ___ the answer.', 'knew', ['know', 'will know'], 'Жаль, что я не знаю ответа.'],
  ['B2', 'wish', 'I wish I ___ said that. It was rude.', 'hadn’t', ['didn’t', 'haven’t'], 'Зря я это сказал. Это было грубо.', { alt: ['had not'] }],
  ['B2', 'wish', 'I wish you ___ stop talking during the film!', 'would', ['will', 'can'], 'Вот бы ты перестал болтать во время фильма!'],
  ['B2', 'passive', 'This bridge ___ in 1890.', 'was built', ['built', 'was build'], 'Этот мост построили в 1890 году.'],
  ['B2', 'passive', 'English ___ in many countries.', 'is spoken', ['speaks', 'is speaking'], 'На английском говорят во многих странах.'],
  ['B2', 'passive', 'Your order ___ right now.', 'is being prepared', ['is preparing', 'prepares'], 'Ваш заказ сейчас готовят.'],
  ['B2', 'reported', 'Yesterday Tom said he ___ come to the party, but he didn’t.', 'would', ['will', 'can'], 'Вчера Том сказал, что придёт на вечеринку, но не пришёл.'],
  ['B2', 'reported', 'She asked me ___ I was ready.', 'if', ['that', 'am'], 'Она спросила, готов ли я.', { alt: ['whether'] }],
  ['B1', 'comparatives', 'This phone is ___ than that one.', 'cheaper', ['more cheap', 'cheapest'], 'Этот телефон дешевле того.'],
  ['B1', 'comparatives', 'It’s the ___ film I’ve ever seen.', 'best', ['better', 'most good'], 'Это лучший фильм, который я когда-либо видел.'],
  ['B1', 'comparatives', 'Travelling by train is ___ than flying.', 'more comfortable', ['comfortabler', 'most comfortable'], 'Путешествовать поездом удобнее, чем летать.'],
  ['B1', 'comparatives', 'Your English is ___ better now!', 'much', ['very', 'more'], 'Твой английский теперь намного лучше!'],
];

const FIXES: FixRow[] = [
  ['B1', 'prep-time', 'We’re going to Spain next summer.', ['We’re going to Spain in next summer.'], 'Следующим летом мы едем в Испанию.'],
  ['B1', 'articles', 'It’s a university in the city centre.', ['It’s an university in the city centre.'], 'Это университет в центре города.'],
  ['B1', 'present-perfect', 'I saw him two days ago.', ['I have seen him two days ago.'], 'Я видел его два дня назад.'],
  ['B1', 'make-do', 'She makes a lot of money.', ['She does a lot of money.'], 'Она зарабатывает много денег.'],
  ['B1', 'to-preposition', 'We’re looking forward to meeting you.', ['We’re looking forward to meet you.'], 'Мы с нетерпением ждём встречи с вами.'],
  ['B2', 'used-to', 'She is used to working late.', ['She is used to work late.', 'She used to working late.'], 'Она привыкла работать допоздна.'],
  ['B1', 'agree', 'I agree with you.', ['I am agree with you.', 'I agree you.'], 'Я с тобой согласен.'],
  ['B1', 'agree', 'I don’t agree with him.', ['I’m not agree with him.'], 'Я с ним не согласен.'],
  ['B1', 'say-tell', 'Can you explain this word to me?', ['Can you explain me this word?'], 'Можешь объяснить мне это слово?'],
  ['B1', 'say-tell', 'She told me about her trip.', ['She said me about her trip.'], 'Она рассказала мне о своей поездке.'],
  ['B1', 'countable', 'We bought some new furniture.', ['We bought some new furnitures.'], 'Мы купили новую мебель.'],
  ['B1', 'conditionals', 'I’ll call you when I get home.', ['I’ll call you when I will get home.'], 'Я позвоню тебе, когда доберусь до дома.'],
  ['B1', 'questions', 'Where do you live?', ['Where you live?', 'Where you do live?'], 'Где ты живёшь?'],
  ['B1', 'questions', 'What did you do yesterday?', ['What you did yesterday?'], 'Что ты делал вчера?'],
  ['B2', 'questions', 'Could you tell me where the station is?', ['Could you tell me where is the station?'], 'Не подскажете, где вокзал?'],
  ['B2', 'questions', 'Do you know what time it is?', ['Do you know what time is it?'], 'Ты не знаешь, который час?'],
  ['B2', 'modals', 'I must go now.', ['I must to go now.'], 'Мне пора идти.'],
  ['B2', 'reported', 'She asked me where I worked.', ['She asked me where did I work.'], 'Она спросила, где я работаю.'],
  ['B2', 'passive', 'The house was built in 1920.', ['The house built in 1920.'], 'Дом построили в 1920 году.'],
  ['B1', 'dep-prep', 'We discussed the plan.', ['We discussed about the plan.'], 'Мы обсудили план.'],
  ['B1', 'prep-place', 'I’ll see you at home.', ['I’ll see you in home.'], 'Увидимся дома.'],
];

export const NO_ARTICLE = NONE;

export const DRILLS: Drill[] = [
  // Ids come from the sentence, so progress survives reordering the lists.
  ...GAPS.map(([level, rule, q, a, wrong, ru, extra]): Drill => ({
    id: `d-${rule}-${hash(q).toString(36)}`,
    kind: 'drill',
    level,
    rule,
    q,
    a,
    wrong,
    ru,
    ...extra,
  })),
  ...FIXES.map(([level, rule, good, bad, ru]): Drill => ({
    id: `f-${rule}-${hash(good).toString(36)}`,
    kind: 'drill',
    level,
    rule,
    q: bad[0],
    a: good,
    wrong: bad,
    ru,
    fix: true,
    typeable: false,
  })),
];
