import { buildVocab, type Row } from './build';

const B1: Row[] = [
  ['It depends.', 'Смотря как. / Зависит от обстоятельств.', 'expr', '— How long does it take? — *It depends* on the traffic.', '— Сколько туда ехать? — Зависит от пробок.', { sit: 'Спрашивают, сколько ехать до центра. Точно сказать нельзя: всё зависит от пробок.', rule: 'dep-prep' }],
  ['Could you say that again?', 'Не могли бы вы повторить?', 'expr', 'Sorry, *could you say that again*? It’s very noisy here.', 'Простите, не могли бы вы повторить? Здесь очень шумно.', { sit: 'Вы не расслышали, что сказал собеседник.' }],
  ['I’m not sure about that.', 'Я в этом не уверен(а).', 'expr', 'Hmm, *I’m not sure about that*. Let’s check.', 'Хм, я в этом не уверен. Давай проверим.', { sit: 'Коллега уверенно называет цифру, но у вас есть сомнения.' }],
  ['That makes sense.', 'Логично. / Теперь понятно.', 'expr', 'Oh, *that makes sense*. Thanks for explaining.', 'А, теперь понятно. Спасибо, что объяснил.', { sit: 'Вам объяснили причину, и всё встало на свои места.', note: 'make sense — иметь смысл (не do sense).', rule: 'make-do' }],
  ['No worries.', 'Ничего страшного. / Не за что.', 'expr', '— Sorry I’m late! — *No worries*, we’ve just started.', '— Извини за опоздание! — Ничего страшного, мы только начали.', { sit: 'Друг извиняется, что опоздал на пять минут.' }],
  ['What do you mean?', 'Что ты имеешь в виду?', 'expr', '*What do you mean*? I don’t understand.', 'Что ты имеешь в виду? Я не понимаю.', { sit: 'Вы не поняли, что хотел сказать собеседник, и просите пояснить.', rule: 'questions' }],
  ['I see what you mean.', 'Понимаю, о чём ты.', 'expr', '*I see what you mean*, but I still disagree.', 'Понимаю, о чём ты, но всё равно не согласен.', { sit: 'Вы поняли мысль собеседника, хотя и не во всём согласны.' }],
  ['Sounds good!', 'Звучит отлично! / Договорились!', 'expr', '— Let’s meet at seven. — *Sounds good*!', '— Давай встретимся в семь. — Отлично!', { sit: 'Друг предлагает встретиться в семь у кинотеатра, вас это устраивает.' }],
  ['I’d rather not.', 'Я бы предпочёл(ла) не… / Лучше не надо.', 'expr', '— Do you want to sing karaoke? — *I’d rather not*.', '— Хочешь спеть в караоке? — Лучше не надо.', { sit: 'Вам предлагают спеть в караоке, а вам совсем не хочется.', note: 'would rather + глагол без to: I’d rather stay home.' }],
  ['Never mind.', 'Неважно. / Не бери в голову.', 'expr', '*Never mind*, I’ve found my keys.', 'Неважно, я нашёл ключи.', { sit: 'Вы попросили помочь найти ключи, но уже сами их нашли.' }],
  ['Let me think.', 'Дай(те) подумать.', 'expr', 'Hmm, *let me think*… Tuesday is better.', 'Хм, дай подумать… Вторник лучше.', { sit: 'Вам задали вопрос, и нужно пару секунд, чтобы ответить.' }],
  ['Go ahead.', 'Давай(те), пожалуйста. (разрешение)', 'expr', '— Can I use your phone? — Sure, *go ahead*.', '— Можно воспользоваться твоим телефоном? — Конечно, давай.', { sit: 'Коллега спрашивает, можно ли взять ваш стул. Вы разрешаете.' }],
  ['It’s up to you.', 'Решай сам(а). / Как хочешь.', 'expr', '— Pizza or sushi? — *It’s up to you*.', '— Пицца или суши? — Решай сам.', { sit: 'Друг спрашивает, куда пойти ужинать. Вам всё равно, пусть решает он.' }],
  ['I’m on my way.', 'Я уже еду. / Я в пути.', 'expr', 'Don’t worry, *I’m on my way*!', 'Не волнуйся, я уже еду!', { sit: 'Вам звонят и спрашивают, где вы. Вы уже вышли из дома.' }],
  ['Take your time.', 'Не торопись.', 'expr', 'There’s no rush, *take your time*.', 'Спешить некуда, не торопись.', { sit: 'Человек нервничает и спешит заполнить анкету. Вы его успокаиваете.' }],
  ['What a pity!', 'Как жаль!', 'expr', '— The concert was cancelled. — *What a pity*!', '— Концерт отменили. — Как жаль!', { sit: 'Вы узнали, что концерт, на который вы собирались, отменили.' }],
  ['I can’t wait!', 'Жду не дождусь!', 'expr', 'We’re going to Italy next week. *I can’t wait*!', 'Мы едем в Италию на следующей неделе. Жду не дождусь!', { sit: 'Скоро отпуск, и вы очень его ждёте.' }],
  ['Help yourself.', 'Угощайтесь. / Берите, не стесняйтесь.', 'expr', 'There’s cake on the table. *Help yourself*!', 'На столе торт. Угощайтесь!', { sit: 'Гости пришли, на столе еда. Вы предлагаете брать без стеснения.' }],
  ['Same here.', 'У меня тоже. / Я тоже.', 'expr', '— I’m so tired today. — *Same here*.', '— Я сегодня так устал. — Я тоже.', { sit: 'Коллега говорит, что устал. Вы чувствуете то же самое.' }],
  ['Could you give me a hand?', 'Можешь мне помочь?', 'expr', '*Could you give me a hand* with these boxes?', 'Можешь помочь мне с этими коробками?', { sit: 'Вам тяжело нести коробки, вы просите соседа помочь.' }],
  ['By the way, …', 'Кстати, …', 'expr', '*By the way*, have you seen Tom recently?', 'Кстати, ты давно видел Тома?', { sit: 'Посреди разговора вы вспомнили о другом и хотите сменить тему.' }],
  ['As far as I know, …', 'Насколько я знаю, …', 'expr', '*As far as I know*, the shop opens at nine.', 'Насколько я знаю, магазин открывается в девять.', { sit: 'Вы не уверены на сто процентов, но думаете, что магазин открывается в девять.' }],
  ['That’s a good point.', 'Хорошее замечание. / Верно подмечено.', 'expr', '*That’s a good point*. I hadn’t thought of that.', 'Верно подмечено. Я об этом не подумал.', { sit: 'Собеседник заметил то, о чём вы не подумали.' }],
  ['What’s the matter?', 'Что случилось?', 'expr', 'You look upset. *What’s the matter*?', 'Ты выглядишь расстроенным. Что случилось?', { sit: 'Подруга выглядит расстроенной. Вы спрашиваете, в чём дело.' }],
  ['Keep in touch!', 'Не пропадай! / Будем на связи!', 'expr', 'It was great to see you. *Keep in touch*!', 'Было здорово увидеться. Не пропадай!', { sit: 'Вы прощаетесь со старым другом, которого давно не видели.' }],
  ['To be honest, …', 'Честно говоря, …', 'expr', '*To be honest*, I didn’t enjoy the party.', 'Честно говоря, вечеринка мне не понравилась.', { sit: 'Вас спрашивают, понравилась ли вечеринка. Вы хотите мягко признаться, что нет.' }],
  ['I’m running late.', 'Я опаздываю.', 'expr', 'Sorry, *I’m running late*. I’ll be there in ten minutes.', 'Извини, я опаздываю. Буду через десять минут.', { sit: 'Вы пишете коллеге, что немного задерживаетесь.' }],
  ['It’s hard to say.', 'Трудно сказать.', 'expr', '— Will it be ready tomorrow? — *It’s hard to say*.', '— Завтра будет готово? — Трудно сказать.', { sit: 'Вас спрашивают о сроках, но вы честно не знаете.' }],
];

const B2: Row[] = [
  ['It’s not a big deal.', 'Ничего страшного. / Пустяки.', 'expr', 'Don’t worry about the cup, *it’s not a big deal*.', 'Не переживай из-за чашки, это пустяки.', { sit: 'Гость разбил дешёвую чашку и очень переживает.' }],
  ['I’m fed up with it.', 'Мне это надоело.', 'expr', 'This rain every day! *I’m fed up with it*.', 'Этот дождь каждый день! Мне надоело.', { sit: 'Уже неделю идёт дождь, и вы устали от этого.', note: 'be fed up WITH something / + -ing.', rule: 'dep-prep' }],
  ['It’s worth a try.', 'Стоит попробовать.', 'expr', 'I’m not sure it’ll work, but *it’s worth a try*.', 'Не уверен, что получится, но попробовать стоит.', { sit: 'Идея может и не сработать, но попытаться имеет смысл.', rule: 'verb-patterns' }],
  ['I couldn’t agree more.', 'Полностью согласен(на).', 'expr', '— We need more breaks. — *I couldn’t agree more*.', '— Нам нужно больше перерывов. — Полностью согласен.', { sit: 'Коллега высказывает мысль, с которой вы согласны на все сто.', rule: 'agree' }],
  ['I’m afraid I can’t make it.', 'Боюсь, я не смогу прийти.', 'expr', 'Thanks for inviting me, but *I’m afraid I can’t make it*.', 'Спасибо за приглашение, но, боюсь, я не смогу прийти.', { sit: 'Вас пригласили на день рождения, но в этот день вы заняты.' }],
  ['Let’s call it a day.', 'На сегодня хватит.', 'expr', 'It’s nearly eight. *Let’s call it a day*.', 'Уже почти восемь. Давайте на сегодня закончим.', { sit: 'Вечер, все устали. Вы предлагаете закончить работу на сегодня.' }],
  ['It slipped my mind.', 'Вылетело из головы.', 'expr', 'Sorry I didn’t call you back, *it slipped my mind*.', 'Прости, что не перезвонил, совсем вылетело из головы.', { sit: 'Вы обещали перезвонить, но забыли. Извиняетесь.' }],
  ['I’ll keep that in mind.', 'Буду иметь в виду.', 'expr', 'Thanks for the tip, *I’ll keep that in mind*.', 'Спасибо за совет, буду иметь в виду.', { sit: 'Вам дали полезный совет на будущее.' }],
  ['That’s out of the question.', 'Об этом не может быть и речи.', 'expr', 'Working on Sunday? *That’s out of the question*.', 'Работать в воскресенье? Об этом не может быть и речи.', { sit: 'Вам предлагают что-то абсолютно неприемлемое.' }],
  ['It’s on the tip of my tongue.', 'Вертится на языке.', 'expr', 'What’s his name? *It’s on the tip of my tongue*!', 'Как его зовут? Вертится на языке!', { sit: 'Вы пытаетесь вспомнить имя актёра и почти вспомнили.' }],
  ['Let’s get to the point.', 'Давайте к делу.', 'expr', 'We don’t have much time, so *let’s get to the point*.', 'У нас мало времени, так что давайте к делу.', { sit: 'Совещание затянулось, и вы предлагаете перейти к главному.' }],
  ['It’s not my cup of tea.', 'Это не моё. / Не в моём вкусе.', 'expr', 'Jazz is great, but *it’s not my cup of tea*.', 'Джаз — это здорово, но не моё.', { sit: 'Вам предлагают пойти на оперу, но вам такое не нравится.' }],
  ['I’ll get back to you.', 'Я вам отвечу позже.', 'expr', 'Let me check my calendar and *I’ll get back to you*.', 'Дайте я посмотрю календарь, и я вам отвечу.', { sit: 'Вам нужно время уточнить детали, прежде чем ответить клиенту.' }],
  ['You’ve got a point.', 'В этом что-то есть. / Ты прав(а).', 'expr', 'Hmm, *you’ve got a point*. Maybe we should wait.', 'Хм, в этом что-то есть. Может, стоит подождать.', { sit: 'Вы спорили, но аргумент собеседника вас убедил.' }],
  ['Better late than never.', 'Лучше поздно, чем никогда.', 'expr', 'I started learning English at fifty. *Better late than never*!', 'Я начал учить английский в пятьдесят. Лучше поздно, чем никогда!', { sit: 'Вы наконец сделали то, что давно откладывали.' }],
  ['It’s a piece of cake.', 'Проще простого.', 'expr', 'Don’t worry about the test, *it’s a piece of cake*.', 'Не волнуйся из-за теста, это проще простого.', { sit: 'Друг боится задания, которое на самом деле очень лёгкое.' }],
  ['Could you be a bit more specific?', 'Можно поконкретнее?', 'expr', 'I don’t follow. *Could you be a bit more specific*?', 'Я не понимаю. Можно поконкретнее?', { sit: 'Вам объясняют слишком общими словами, нужны детали.' }],
  ['Let me get this straight.', 'Давай уточню. / Правильно ли я понимаю…', 'expr', '*Let me get this straight*: you want me to work on Saturday?', 'Давай уточню: ты хочешь, чтобы я работал в субботу?', { sit: 'Вы хотите убедиться, что правильно поняли неожиданную просьбу.' }],
  ['Fair enough.', 'Справедливо. / Ладно, принимается.', 'expr', '— I can’t come, I’m working. — *Fair enough*.', '— Я не могу прийти, я работаю. — Понятно, справедливо.', { sit: 'Друг объяснил причину отказа, и вы её принимаете.' }],
  ['I didn’t catch that.', 'Я не расслышал(а). / Не уловил(а).', 'expr', 'Sorry, *I didn’t catch that*. What was your name?', 'Простите, я не расслышал. Как вас зовут?', { sit: 'Вам представились, но вы не расслышали имя.' }],
  ['It’s no use.', 'Бесполезно.', 'expr', '*It’s no use* trying to persuade him.', 'Бесполезно пытаться его переубедить.', { sit: 'Вы пытались уговорить упрямого человека, но ничего не выходит.', note: 'It’s no use + -ing.', rule: 'verb-patterns' }],
  ['Don’t get me wrong.', 'Не пойми меня неправильно.', 'expr', '*Don’t get me wrong*, I like your idea, but it’s too expensive.', 'Не пойми меня неправильно, идея мне нравится, но это слишком дорого.', { sit: 'Вы хотите покритиковать план, но не обидеть автора.' }],
];

export const PHRASES = [...buildVocab('B1', 'phrase', B1), ...buildVocab('B2', 'phrase', B2)];
