import { buildVocab, type Row } from './build';

const ROWS: Row[] = [
  ['accurate', 'точный', 'adj', 'The weather forecast was surprisingly *accurate*.', 'Прогноз погоды оказался на удивление точным.', { note: 'Not «аккуратный» — that is neat or tidy.', rule: 'false-friends' }],
  ['actually', 'на самом деле, вообще-то', 'adv', '*Actually*, I’ve changed my mind.', 'Вообще-то я передумал.', { note: 'Not «актуально» — that is relevant.', rule: 'false-friends' }],
  ['approach', 'подход; приближаться', 'n', 'We need a different *approach* to this problem.', 'Нам нужен другой подход к этой проблеме.', { note: 'an approach TO a problem; approach a place — no preposition.' }],
  ['assume', 'предполагать, считать', 'v', 'I *assume* you’ve already heard the news.', 'Полагаю, ты уже слышал новости.'],
  ['awareness', 'осведомлённость, понимание', 'n', 'There is growing *awareness* of climate issues.', 'Растёт понимание проблем климата.'],
  ['benefit', 'польза, выгода', 'n', 'One *benefit* of working from home is no commute.', 'Одно из преимуществ работы из дома — не нужно ездить в офис.'],
  ['challenge', 'трудная задача, вызов', 'n', 'Learning a language is a real *challenge*.', 'Выучить язык — настоящее испытание.'],
  ['complicated', 'сложный, запутанный', 'adj', 'The instructions were too *complicated*.', 'Инструкция была слишком запутанной.'],
  ['consequence', 'последствие', 'n', 'He had to face the *consequences* of his decision.', 'Ему пришлось столкнуться с последствиями своего решения.'],
  ['consider', 'рассматривать, обдумывать', 'v', 'Have you *considered* moving abroad?', 'Ты не думал переехать за границу?', { note: 'consider + -ing.', rule: 'verb-patterns' }],
  ['convince', 'убеждать (в чём-то)', 'v', 'She *convinced* me that she was right.', 'Она убедила меня, что права.', { note: 'convince someone OF something / that…' }],
  ['crucial', 'ключевой, решающий', 'adj', 'The next few days are *crucial*.', 'Следующие несколько дней будут решающими.'],
  ['deadline', 'крайний срок, дедлайн', 'n', 'The *deadline* for the project is Friday.', 'Крайний срок по проекту — пятница.', { note: 'meet a deadline = finish in time; miss a deadline = be late.' }],
  ['deny', 'отрицать', 'v', 'He *denied* taking the money.', 'Он отрицал, что взял деньги.', { note: 'deny + -ing.', rule: 'verb-patterns' }],
  ['determined', 'полный решимости', 'adj', 'She was *determined* to win.', 'Она была полна решимости победить.'],
  ['efficient', 'эффективный (без потерь)', 'adj', 'The new system is much more *efficient*.', 'Новая система гораздо эффективнее.'],
  ['eventually', 'в конце концов, в итоге', 'adv', 'We *eventually* found the hotel.', 'В итоге мы нашли отель.', { note: 'Not «возможно» — that is possibly.', rule: 'false-friends' }],
  ['evidence', 'доказательства, улики', 'n', 'There is no *evidence* that he was there.', 'Нет никаких доказательств, что он был там.', { note: 'Uncountable: a piece of evidence.', rule: 'countable' }],
  ['exaggerate', 'преувеличивать', 'v', 'Don’t *exaggerate*, it wasn’t that bad!', 'Не преувеличивай, всё было не так уж плохо!'],
  ['feature', 'особенность, функция', 'n', 'The new phone has some useful *features*.', 'У нового телефона есть полезные функции.'],
  ['flexible', 'гибкий', 'adj', 'I have *flexible* working hours.', 'У меня гибкий рабочий график.'],
  ['genuine', 'настоящий, искренний', 'adj', 'She showed *genuine* interest in my work.', 'Она проявила искренний интерес к моей работе.'],
  ['hesitate', 'колебаться, стесняться (сделать)', 'v', 'Don’t *hesitate* to call me if you need help.', 'Не стесняйтесь звонить, если понадобится помощь.'],
  ['impact', 'влияние, воздействие', 'n', 'Social media has a huge *impact* on our lives.', 'Соцсети сильно влияют на нашу жизнь.', { note: 'impact ON something.', rule: 'dep-prep' }],
  ['inevitable', 'неизбежный', 'adj', 'Some mistakes are *inevitable* when you learn.', 'Когда учишься, некоторые ошибки неизбежны.'],
  ['insist', 'настаивать', 'v', 'He *insisted* on paying for dinner.', 'Он настоял на том, чтобы заплатить за ужин.', { note: 'insist ON + -ing.', rule: 'dep-prep' }],
  ['involve', 'включать в себя; вовлекать', 'v', 'The job *involves* a lot of travelling.', 'Эта работа связана с частыми поездками.', { note: 'involve + -ing.', rule: 'verb-patterns' }],
  ['issue', 'вопрос, проблема', 'n', 'Let’s discuss this *issue* at the meeting.', 'Давайте обсудим этот вопрос на совещании.', { note: 'discuss something — no about.' }],
  ['likely', 'вероятный', 'adj', 'It’s *likely* to rain later.', 'Скорее всего, позже пойдёт дождь.', { note: 'be likely to do.' }],
  ['maintain', 'поддерживать, сохранять', 'v', 'It’s hard to *maintain* a healthy lifestyle.', 'Трудно поддерживать здоровый образ жизни.'],
  ['negotiate', 'вести переговоры, договариваться', 'v', 'We *negotiated* a better price.', 'Мы договорились о более выгодной цене.'],
  ['obvious', 'очевидный', 'adj', 'The answer seems *obvious* now.', 'Теперь ответ кажется очевидным.'],
  ['occasionally', 'изредка, время от времени', 'adv', 'I *occasionally* go to the theatre.', 'Я изредка хожу в театр.'],
  ['outcome', 'исход, результат', 'n', 'We’re waiting for the *outcome* of the negotiations.', 'Мы ждём исхода переговоров.'],
  ['overcome', 'преодолеть', 'v', 'She *overcame* her fear of flying.', 'Она преодолела страх полётов.'],
  ['particular', 'особый, конкретный', 'adj', 'Is there any *particular* reason you’re asking?', 'Ты спрашиваешь по какой-то особой причине?', { note: 'in particular = especially.' }],
  ['permanent', 'постоянный', 'adj', 'Is this a *permanent* job or a temporary one?', 'Это постоянная работа или временная?'],
  ['postpone', 'откладывать, переносить', 'v', 'The match was *postponed* because of the rain.', 'Матч перенесли из-за дождя.'],
  ['predict', 'предсказывать', 'v', 'Nobody can *predict* the future.', 'Никто не может предсказать будущее.'],
  ['priority', 'приоритет', 'n', 'My family is my top *priority*.', 'Семья для меня на первом месте.'],
  ['pursue', 'стремиться к, заниматься (целью)', 'v', 'She decided to *pursue* a career in law.', 'Она решила строить карьеру в юриспруденции.'],
  ['reluctant', 'неохотный, не желающий', 'adj', 'He was *reluctant* to admit his mistake.', 'Ему не хотелось признавать свою ошибку.'],
  ['rely', 'полагаться', 'v', 'You can always *rely* on me.', 'Ты всегда можешь на меня положиться.', { note: 'rely ON.', rule: 'dep-prep' }],
  ['remarkable', 'замечательный, выдающийся', 'adj', 'She made a *remarkable* recovery.', 'Она поразительно быстро поправилась.'],
  ['require', 'требовать(ся)', 'v', 'This job *requires* a lot of patience.', 'Эта работа требует большого терпения.'],
  ['resign', 'уволиться (по собственному), уйти в отставку', 'v', 'He *resigned* after ten years at the company.', 'Он уволился после десяти лет в компании.'],
  ['responsible', 'ответственный', 'adj', 'Who is *responsible* for this mess?', 'Кто отвечает за этот бардак?', { note: 'responsible FOR.', rule: 'dep-prep' }],
  ['significant', 'значительный, важный', 'adj', 'There has been a *significant* increase in prices.', 'Цены значительно выросли.'],
  ['struggle', 'бороться, с трудом справляться', 'v', 'I *struggled* to understand his accent.', 'Я с трудом понимал его акцент.', { note: 'struggle + to do / struggle WITH something.' }],
  ['sufficient', 'достаточный', 'adj', 'We don’t have *sufficient* information.', 'У нас недостаточно информации.'],
  ['suspect', 'подозревать', 'v', 'I *suspect* he’s not telling the truth.', 'Подозреваю, что он говорит неправду.', { note: 'suspect someone OF something.' }],
  ['tend', 'иметь склонность, обычно (делать)', 'v', 'I *tend* to eat too much when I’m stressed.', 'Когда я в стрессе, я обычно переедаю.', { note: 'tend + to do.', rule: 'verb-patterns' }],
  ['thorough', 'тщательный', 'adj', 'The police carried out a *thorough* search.', 'Полиция провела тщательный обыск.'],
  ['threat', 'угроза', 'n', 'Climate change is a serious *threat*.', 'Изменение климата — серьёзная угроза.'],
  ['vary', 'различаться, меняться', 'v', 'Prices *vary* from shop to shop.', 'Цены отличаются от магазина к магазину.'],
  ['willing', 'готовый, согласный (сделать)', 'adj', 'Are you *willing* to work at weekends?', 'Вы готовы работать по выходным?', { note: 'be willing to do.' }],
  ['withdraw', 'снимать (деньги); отзывать', 'v', 'I need to *withdraw* some cash.', 'Мне нужно снять наличные.'],
  ['worth', 'стоящий, стоит (сделать)', 'adj', 'The film is *worth* watching.', 'Этот фильм стоит посмотреть.', { note: 'be worth + -ing.', rule: 'verb-patterns' }],
  ['ambitious', 'честолюбивый, амбициозный', 'adj', 'It’s an *ambitious* plan, but I think it’ll work.', 'Это амбициозный план, но, думаю, он сработает.'],
  ['apparently', 'судя по всему, по-видимому', 'adv', '*Apparently*, they’re getting married.', 'Говорят, они женятся.', { note: 'Not «очевидно» — that is obviously.', rule: 'false-friends' }],
  ['appreciate', 'ценить, быть признательным', 'v', 'I really *appreciate* your help.', 'Я очень ценю твою помощь.', { note: 'appreciate something — no for.' }],
  ['argument', 'спор, ссора; довод', 'n', 'We had an *argument* about money.', 'Мы поссорились из-за денег.'],
  ['brief', 'краткий, короткий', 'adj', 'Could you give us a *brief* summary?', 'Не могли бы вы кратко подвести итог?'],
  ['commute', 'ездить на работу (и обратно)', 'v', 'I *commute* to work by train.', 'Я езжу на работу на поезде.'],
  ['contribute', 'вносить вклад', 'v', 'Everyone *contributed* to the project.', 'Каждый внёс вклад в проект.', { note: 'contribute TO.', rule: 'dep-prep' }],
  ['delay', 'задержка; задерживать', 'n', 'Sorry for the *delay*.', 'Извините за задержку.'],
  ['encourage', 'поощрять, подбадривать', 'v', 'My parents *encouraged* me to learn languages.', 'Родители поощряли меня учить языки.', { note: 'encourage someone to do.' }],
  ['estimate', 'оценивать (примерно)', 'v', 'Can you *estimate* how much it will cost?', 'Можете примерно оценить, сколько это будет стоить?'],
  ['fascinating', 'захватывающий, очень интересный', 'adj', 'It was a *fascinating* documentary.', 'Это был захватывающий документальный фильм.', { rule: 'ed-ing' }],
  ['frustrated', 'раздосадованный (от бессилия)', 'adj', 'I get *frustrated* when my computer freezes.', 'Меня бесит, когда компьютер зависает.', { rule: 'ed-ing' }],
  ['gradually', 'постепенно', 'adv', 'My English is *gradually* getting better.', 'Мой английский постепенно становится лучше.'],
  ['guarantee', 'гарантировать; гарантия', 'v', 'We can’t *guarantee* that the tickets will be available.', 'Мы не можем гарантировать, что билеты будут.'],
  ['income', 'доход', 'n', 'They live on a low *income*.', 'Они живут на небольшой доход.'],
  ['mortgage', 'ипотека', 'n', 'We took out a *mortgage* to buy the flat.', 'Мы взяли ипотеку, чтобы купить квартиру.', { note: 'The t is silent: [ˈmɔːɡɪdʒ].' }],
  ['obstacle', 'препятствие', 'n', 'Lack of money was the main *obstacle*.', 'Главным препятствием была нехватка денег.'],
  ['recover', 'выздороветь, восстановиться', 'v', 'It took me a week to *recover* from the flu.', 'Мне понадобилась неделя, чтобы оправиться от гриппа.', { note: 'recover FROM.', rule: 'dep-prep' }],
  ['relevant', 'актуальный, относящийся к делу', 'adj', 'This information is no longer *relevant*.', 'Эта информация больше не актуальна.', { note: '«Актуальный» in English is relevant or up to date, not actual.', rule: 'false-friends' }],
  ['reputation', 'репутация', 'n', 'The restaurant has a good *reputation*.', 'У ресторана хорошая репутация.'],
  ['sympathetic', 'сочувствующий, понимающий', 'adj', 'She was very *sympathetic* when I told her about my problems.', 'Она очень мне сочувствовала, когда я рассказал о своих проблемах.', { note: 'Not «симпатичный» — that is nice or good-looking.', rule: 'false-friends' }],
  ['tough', 'трудный, жёсткий', 'adj', 'It was a *tough* decision.', 'Это было трудное решение.'],
  ['vulnerable', 'уязвимый', 'adj', 'Old people are more *vulnerable* to the flu.', 'Пожилые люди более уязвимы для гриппа.'],
  ['wealthy', 'богатый, состоятельный', 'adj', 'He comes from a *wealthy* family.', 'Он из состоятельной семьи.'],
  ['fabric', 'ткань', 'n', 'This *fabric* is easy to wash.', 'Эту ткань легко стирать.', { note: 'Фабрика is a factory.', rule: 'false-friends' }],
  ['decade', 'десятилетие', 'n', 'The city has changed a lot over the last *decade*.', 'Город сильно изменился за последнее десятилетие.', { note: 'decade = 10 years, not 10 days.', rule: 'false-friends' }],
  ['anxious', 'тревожный, встревоженный', 'adj', 'I’m *anxious* about the results.', 'Я переживаю из-за результатов.', { note: 'anxious ABOUT something; be anxious to do = want very much to do.' }],
  ['cope', 'справляться', 'v', 'How do you *cope* with stress?', 'Как ты справляешься со стрессом?', { note: 'cope WITH.' }],
  ['reveal', 'раскрывать, обнаруживать', 'v', 'He refused to *reveal* his name.', 'Он отказался назвать своё имя.'],
  ['strict', 'строгий', 'adj', 'My parents were very *strict*.', 'Мои родители были очень строгими.'],
  ['come up with', 'придумать (идею, план)', 'phr v', 'She *came up with* a brilliant idea.', 'Она придумала блестящую идею.'],
  ['carry out', 'проводить, выполнять', 'phr v', 'The survey was *carried out* last month.', 'Опрос провели в прошлом месяце.'],
  ['put up with', 'терпеть, мириться', 'phr v', 'I can’t *put up with* this noise any longer.', 'Я больше не могу терпеть этот шум.'],
  ['look into', 'изучить, разобраться', 'phr v', 'We’ll *look into* the problem.', 'Мы разберёмся с этой проблемой.'],
  ['bring up', 'воспитывать; поднимать (тему)', 'phr v', 'She was *brought up* by her grandparents.', 'Её воспитали бабушка и дедушка.'],
  ['turn out', 'оказаться', 'phr v', 'It *turned out* that he was right.', 'Оказалось, что он был прав.'],
  ['take over', 'взять на себя, перенять', 'phr v', 'Can you *take over* while I’m on holiday?', 'Можешь взять мои дела, пока я в отпуске?'],
  ['get over', 'пережить, оправиться', 'phr v', 'It took her months to *get over* the break-up.', 'Ей понадобились месяцы, чтобы пережить расставание.'],
  ['cut down on', 'сократить (потребление)', 'phr v', 'I’m trying to *cut down on* sugar.', 'Я стараюсь есть меньше сахара.'],
  ['figure out', 'понять, разобраться', 'phr v', 'I can’t *figure out* how this works.', 'Не могу понять, как это работает.'],
];

export const WORDS_B2 = buildVocab('B2', 'word', ROWS);
