import { buildVocab, type Row } from './build';

const ROWS: Row[] = [
  ['accurate', 'точный', 'adj', 'The weather forecast was surprisingly *accurate*.', 'Прогноз погоды оказался на удивление точным.', { note: 'Not «аккуратный» — that is neat or tidy.', rule: 'false-friends' }],
  ['actually', 'на самом деле, вообще-то', 'adv', '*Actually*, I’ve changed my mind.', 'Вообще-то я передумал.', { note: 'Not «актуально» — that is relevant.', rule: 'false-friends' }],
  ['approach', 'подход; приближаться', 'n', 'We need a different *approach* to this problem.', 'Нам нужен другой подход к этой проблеме.', { note: 'an approach TO a problem; approach a place — no preposition.' }],
  ['assume', 'предполагать, считать', 'v', 'I *assume* you’ve already heard the news.', 'Полагаю, ты уже слышал новости.'],
  ['awareness', 'осведомлённость, понимание', 'n', 'There is growing *awareness* of climate issues.', 'Растёт понимание проблем климата.'],
  ['benefit', 'польза, выгода', 'n', 'One *benefit* of working from home is no commute.', 'Одно из преимуществ работы из дома — не нужно ездить в офис.'],
  ['challenge', 'трудная задача, вызов', 'n', 'Learning a language is a real *challenge*.', 'Выучить язык — настоящее испытание.'],
  ['complicated', 'сложный, запутанный', 'adj', 'The instructions were too *complicated*.', 'Инструкция была слишком запутанной.'],
  ['consequence', 'последствие', 'n', 'He had to face the *consequences* of his decision.', 'Ему пришлось столкнуться с последствиями своего решения.'],
  ['consider', 'рассматривать, обдумывать', 'v', 'Have you *considered* moving abroad?', 'Ты не думал переехать за границу?', { note: 'consider + -ing.', rule: 'verb-patterns' }],
  ['convince', 'убеждать (в чём-то)', 'v', 'She *convinced* me that she was right.', 'Она убедила меня, что права.', { note: 'convince someone OF something / that…' }],
  ['crucial', 'ключевой, решающий', 'adj', 'The next few days are *crucial*.', 'Следующие несколько дней будут решающими.'],
  ['deadline', 'крайний срок, дедлайн', 'n', 'The *deadline* for the project is Friday.', 'Крайний срок по проекту — пятница.', { note: 'meet a deadline = finish in time; miss a deadline = be late.' }],
  ['deny', 'отрицать', 'v', 'He *denied* taking the money.', 'Он отрицал, что взял деньги.', { note: 'deny + -ing.', rule: 'verb-patterns' }],
  ['determined', 'полный решимости', 'adj', 'She was *determined* to win.', 'Она была полна решимости победить.'],
  ['efficient', 'эффективный (без потерь)', 'adj', 'The new system is much more *efficient*.', 'Новая система гораздо эффективнее.'],
  ['eventually', 'в конце концов, в итоге', 'adv', 'We *eventually* found the hotel.', 'В итоге мы нашли отель.', { note: 'Not «возможно» — that is possibly.', rule: 'false-friends' }],
  ['evidence', 'доказательства, улики', 'n', 'There is no *evidence* that he was there.', 'Нет никаких доказательств, что он был там.', { note: 'Uncountable: a piece of evidence.', rule: 'countable' }],
  ['exaggerate', 'преувеличивать', 'v', 'Don’t *exaggerate*, it wasn’t that bad!', 'Не преувеличивай, всё было не так уж плохо!'],
  ['feature', 'особенность, функция', 'n', 'The new phone has some useful *features*.', 'У нового телефона есть полезные функции.'],
  ['flexible', 'гибкий', 'adj', 'I have *flexible* working hours.', 'У меня гибкий рабочий график.'],
  ['genuine', 'настоящий, искренний', 'adj', 'She showed *genuine* interest in my work.', 'Она проявила искренний интерес к моей работе.'],
  ['hesitate', 'колебаться, стесняться (сделать)', 'v', 'Don’t *hesitate* to call me if you need help.', 'Не стесняйтесь звонить, если понадобится помощь.'],
  ['impact', 'влияние, воздействие', 'n', 'Social media has a huge *impact* on our lives.', 'Соцсети сильно влияют на нашу жизнь.', { note: 'impact ON something.', rule: 'dep-prep' }],
  ['inevitable', 'неизбежный', 'adj', 'Some mistakes are *inevitable* when you learn.', 'Когда учишься, некоторые ошибки неизбежны.'],
  ['insist', 'настаивать', 'v', 'He *insisted* on paying for dinner.', 'Он настоял на том, чтобы заплатить за ужин.', { note: 'insist ON + -ing.', rule: 'dep-prep' }],
  ['involve', 'включать в себя; вовлекать', 'v', 'The job *involves* a lot of travelling.', 'Эта работа связана с частыми поездками.', { note: 'involve + -ing.', rule: 'verb-patterns' }],
  ['issue', 'вопрос, проблема', 'n', 'Let’s discuss this *issue* at the meeting.', 'Давайте обсудим этот вопрос на совещании.', { note: 'discuss something — no about.' }],
  ['likely', 'вероятный', 'adj', 'It’s *likely* to rain later.', 'Скорее всего, позже пойдёт дождь.', { note: 'be likely to do.' }],
  ['maintain', 'поддерживать, сохранять', 'v', 'It’s hard to *maintain* a healthy lifestyle.', 'Трудно поддерживать здоровый образ жизни.'],
  ['negotiate', 'вести переговоры, договариваться', 'v', 'We *negotiated* a better price.', 'Мы договорились о более выгодной цене.'],
  ['obvious', 'очевидный', 'adj', 'The answer seems *obvious* now.', 'Теперь ответ кажется очевидным.'],
  ['occasionally', 'изредка, время от времени', 'adv', 'I *occasionally* go to the theatre.', 'Я изредка хожу в театр.'],
  ['outcome', 'исход, результат', 'n', 'We’re waiting for the *outcome* of the negotiations.', 'Мы ждём исхода переговоров.'],
  ['overcome', 'преодолеть', 'v', 'She *overcame* her fear of flying.', 'Она преодолела страх полётов.'],
  ['particular', 'особый, конкретный', 'adj', 'Is there any *particular* reason you’re asking?', 'Ты спрашиваешь по какой-то особой причине?', { note: 'in particular = especially.' }],
  ['permanent', 'постоянный', 'adj', 'Is this a *permanent* job or a temporary one?', 'Это постоянная работа или временная?'],
  ['postpone', 'откладывать, переносить', 'v', 'The match was *postponed* because of the rain.', 'Матч перенесли из-за дождя.'],
  ['predict', 'предсказывать', 'v', 'Nobody can *predict* the future.', 'Никто не может предсказать будущее.'],
  ['priority', 'приоритет', 'n', 'My family is my top *priority*.', 'Семья для меня на первом месте.'],
  ['pursue', 'стремиться к, заниматься (целью)', 'v', 'She decided to *pursue* a career in law.', 'Она решила строить карьеру в юриспруденции.'],
  ['reluctant', 'неохотный, не желающий', 'adj', 'He was *reluctant* to admit his mistake.', 'Ему не хотелось признавать свою ошибку.'],
  ['rely', 'полагаться', 'v', 'You can always *rely* on me.', 'Ты всегда можешь на меня положиться.', { note: 'rely ON.', rule: 'dep-prep' }],
  ['remarkable', 'замечательный, выдающийся', 'adj', 'She made a *remarkable* recovery.', 'Она поразительно быстро поправилась.'],
  ['require', 'требовать(ся)', 'v', 'This job *requires* a lot of patience.', 'Эта работа требует большого терпения.'],
  ['resign', 'уволиться (по собственному), уйти в отставку', 'v', 'He *resigned* after ten years at the company.', 'Он уволился после десяти лет в компании.'],
  ['responsible', 'ответственный', 'adj', 'Who is *responsible* for this mess?', 'Кто отвечает за этот бардак?', { note: 'responsible FOR.', rule: 'dep-prep' }],
  ['significant', 'значительный, важный', 'adj', 'There has been a *significant* increase in prices.', 'Цены значительно выросли.'],
  ['struggle', 'бороться, с трудом справляться', 'v', 'I *struggled* to understand his accent.', 'Я с трудом понимал его акцент.', { note: 'struggle + to do / struggle WITH something.' }],
  ['sufficient', 'достаточный', 'adj', 'We don’t have *sufficient* information.', 'У нас недостаточно информации.'],
  ['suspect', 'подозревать', 'v', 'I *suspect* he’s not telling the truth.', 'Подозреваю, что он говорит неправду.', { note: 'suspect someone OF something.' }],
  ['tend', 'иметь склонность, обычно (делать)', 'v', 'I *tend* to eat too much when I’m stressed.', 'Когда я в стрессе, я обычно переедаю.', { note: 'tend + to do.', rule: 'verb-patterns' }],
  ['thorough', 'тщательный', 'adj', 'The police carried out a *thorough* search.', 'Полиция провела тщательный обыск.'],
  ['threat', 'угроза', 'n', 'Climate change is a serious *threat*.', 'Изменение климата — серьёзная угроза.'],
  ['vary', 'различаться, меняться', 'v', 'Prices *vary* from shop to shop.', 'Цены отличаются от магазина к магазину.'],
  ['willing', 'готовый, согласный (сделать)', 'adj', 'Are you *willing* to work at weekends?', 'Вы готовы работать по выходным?', { note: 'be willing to do.' }],
  ['withdraw', 'снимать (деньги); отзывать', 'v', 'I need to *withdraw* some cash.', 'Мне нужно снять наличные.'],
  ['worth', 'стоящий, стоит (сделать)', 'adj', 'The film is *worth* watching.', 'Этот фильм стоит посмотреть.', { note: 'be worth + -ing.', rule: 'verb-patterns' }],
  ['ambitious', 'честолюбивый, амбициозный', 'adj', 'It’s an *ambitious* plan, but I think it’ll work.', 'Это амбициозный план, но, думаю, он сработает.'],
  ['apparently', 'судя по всему, по-видимому', 'adv', '*Apparently*, they’re getting married.', 'Говорят, они женятся.', { note: 'Not «очевидно» — that is obviously.', rule: 'false-friends' }],
  ['appreciate', 'ценить, быть признательным', 'v', 'I really *appreciate* your help.', 'Я очень ценю твою помощь.', { note: 'appreciate something — no for.' }],
  ['argument', 'спор, ссора; довод', 'n', 'We had an *argument* about money.', 'Мы поссорились из-за денег.'],
  ['brief', 'краткий, короткий', 'adj', 'Could you give us a *brief* summary?', 'Не могли бы вы кратко подвести итог?'],
  ['commute', 'ездить на работу (и обратно)', 'v', 'I *commute* to work by train.', 'Я езжу на работу на поезде.'],
  ['contribute', 'вносить вклад', 'v', 'Everyone *contributed* to the project.', 'Каждый внёс вклад в проект.', { note: 'contribute TO.', rule: 'dep-prep' }],
  ['delay', 'задержка; задерживать', 'n', 'Sorry for the *delay*.', 'Извините за задержку.'],
  ['encourage', 'поощрять, подбадривать', 'v', 'My parents *encouraged* me to learn languages.', 'Родители поощряли меня учить языки.', { note: 'encourage someone to do.' }],
  ['estimate', 'оценивать (примерно)', 'v', 'Can you *estimate* how much it will cost?', 'Можете примерно оценить, сколько это будет стоить?'],
  ['fascinating', 'захватывающий, очень интересный', 'adj', 'It was a *fascinating* documentary.', 'Это был захватывающий документальный фильм.', { rule: 'ed-ing' }],
  ['frustrated', 'раздосадованный (от бессилия)', 'adj', 'I get *frustrated* when my computer freezes.', 'Меня бесит, когда компьютер зависает.', { rule: 'ed-ing' }],
  ['gradually', 'постепенно', 'adv', 'My English is *gradually* getting better.', 'Мой английский постепенно становится лучше.'],
  ['guarantee', 'гарантировать; гарантия', 'v', 'We can’t *guarantee* that the tickets will be available.', 'Мы не можем гарантировать, что билеты будут.'],
  ['income', 'доход', 'n', 'They live on a low *income*.', 'Они живут на небольшой доход.'],
  ['mortgage', 'ипотека', 'n', 'We took out a *mortgage* to buy the flat.', 'Мы взяли ипотеку, чтобы купить квартиру.', { note: 'The t is silent: [ˈmɔːɡɪdʒ].' }],
  ['obstacle', 'препятствие', 'n', 'Lack of money was the main *obstacle*.', 'Главным препятствием была нехватка денег.'],
  ['recover', 'выздороветь, восстановиться', 'v', 'It took me a week to *recover* from the flu.', 'Мне понадобилась неделя, чтобы оправиться от гриппа.', { note: 'recover FROM.', rule: 'dep-prep' }],
  ['relevant', 'актуальный, относящийся к делу', 'adj', 'This information is no longer *relevant*.', 'Эта информация больше не актуальна.', { note: '«Актуальный» in English is relevant or up to date, not actual.', rule: 'false-friends' }],
  ['reputation', 'репутация', 'n', 'The restaurant has a good *reputation*.', 'У ресторана хорошая репутация.'],
  ['sympathetic', 'сочувствующий, понимающий', 'adj', 'She was very *sympathetic* when I told her about my problems.', 'Она очень мне сочувствовала, когда я рассказал о своих проблемах.', { note: 'Not «симпатичный» — that is nice or good-looking.', rule: 'false-friends' }],
  ['tough', 'трудный, жёсткий', 'adj', 'It was a *tough* decision.', 'Это было трудное решение.'],
  ['vulnerable', 'уязвимый', 'adj', 'Old people are more *vulnerable* to the flu.', 'Пожилые люди более уязвимы для гриппа.'],
  ['wealthy', 'богатый, состоятельный', 'adj', 'He comes from a *wealthy* family.', 'Он из состоятельной семьи.'],
  ['fabric', 'ткань', 'n', 'This *fabric* is easy to wash.', 'Эту ткань легко стирать.', { note: 'Фабрика is a factory.', rule: 'false-friends' }],
  ['decade', 'десятилетие', 'n', 'The city has changed a lot over the last *decade*.', 'Город сильно изменился за последнее десятилетие.', { note: 'decade = 10 years, not 10 days.', rule: 'false-friends' }],
  ['anxious', 'тревожный, встревоженный', 'adj', 'I’m *anxious* about the results.', 'Я переживаю из-за результатов.', { note: 'anxious ABOUT something; be anxious to do = want very much to do.' }],
  ['cope', 'справляться', 'v', 'How do you *cope* with stress?', 'Как ты справляешься со стрессом?', { note: 'cope WITH.' }],
  ['reveal', 'раскрывать, обнаруживать', 'v', 'He refused to *reveal* his name.', 'Он отказался назвать своё имя.'],
  ['strict', 'строгий', 'adj', 'My parents were very *strict*.', 'Мои родители были очень строгими.'],
  // Frequent verbs
  ['acknowledge', 'признавать', 'v', 'It’s important to *acknowledge* your feelings.', 'Важно признавать свои чувства.'],
  ['adapt', 'приспосабливаться, адаптироваться', 'v', 'It took us a year to *adapt* to life abroad.', 'Нам понадобился год, чтобы привыкнуть к жизни за границей.', { note: 'adapt TO something.' }],
  ['adjust', 'привыкать; настраивать', 'v', 'Children *adjust* quickly to a new school.', 'Дети быстро привыкают к новой школе.', { note: 'adjust TO something.' }],
  ['attempt', 'пытаться; попытка', 'v', 'He *attempted* to fix the car himself.', 'Он попытался сам починить машину.'],
  ['bother', 'беспокоить, волновать', 'v', 'What’s *bothering* you?', 'Что тебя беспокоит?'],
  ['claim', 'утверждать', 'v', 'He *claims* he didn’t see anything.', 'Он утверждает, что ничего не видел.'],
  ['commit', 'брать обязательства; совершать', 'v', 'I’m not ready to *commit* to a relationship.', 'Я не готов к серьёзным отношениям.', { note: 'commit TO something; commit a crime.' }],
  ['comfort', 'утешать', 'v', 'She tried to *comfort* her crying son.', 'Она пыталась утешить плачущего сына.'],
  ['concentrate', 'сосредоточиться', 'v', 'I can’t *concentrate* when it’s noisy.', 'Я не могу сосредоточиться, когда шумно.', { note: 'concentrate ON something.', rule: 'dep-prep' }],
  ['confirm', 'подтверждать', 'v', 'Please *confirm* your booking by email.', 'Пожалуйста, подтвердите бронирование по электронной почте.'],
  ['criticise', 'критиковать', 'v', 'He’s always *criticising* me.', 'Он всё время меня критикует.', { alt: ['criticize'] }],
  ['ensure', 'обеспечивать, следить (чтобы)', 'v', 'Please *ensure* that all the doors are locked.', 'Пожалуйста, убедитесь, что все двери заперты.'],
  ['establish', 'устанавливать, основывать', 'v', 'It takes time to *establish* trust.', 'Чтобы установить доверие, нужно время.'],
  ['explore', 'исследовать, изучать', 'v', 'Let’s *explore* why you feel this way.', 'Давайте разберёмся, почему вы так себя чувствуете.'],
  ['heal', 'заживать; исцелять', 'v', 'Time *heals* all wounds.', 'Время лечит все раны.'],
  ['highlight', 'подчёркивать, выделять', 'v', 'The report *highlights* several problems.', 'В отчёте выделено несколько проблем.'],
  ['imply', 'подразумевать, намекать', 'v', 'Are you *implying* that I’m lazy?', 'Ты намекаешь, что я ленивый?'],
  ['interpret', 'толковать, понимать', 'v', 'How do you *interpret* this dream?', 'Как вы толкуете этот сон?'],
  ['justify', 'оправдывать', 'v', 'Nothing can *justify* violence.', 'Ничто не может оправдать насилие.'],
  ['perceive', 'воспринимать', 'v', 'How do you think others *perceive* you?', 'Как, по-вашему, вас воспринимают другие?'],
  ['react', 'реагировать', 'v', 'How did she *react* to the news?', 'Как она отреагировала на новость?', { note: 'react TO something.', rule: 'dep-prep' }],
  ['reassure', 'успокоить, заверить', 'v', 'The doctor *reassured* me that it was nothing serious.', 'Врач заверил меня, что ничего серьёзного нет.'],
  ['reflect', 'размышлять; отражать', 'v', 'Take a moment to *reflect* on what happened.', 'Найдите минуту, чтобы поразмышлять о том, что произошло.', { note: 'reflect ON something.' }],
  ['reject', 'отвергать, отклонять', 'v', 'She was afraid he would *reject* her.', 'Она боялась, что он её отвергнет.'],
  ['resolve', 'разрешать, улаживать', 'v', 'They *resolved* the conflict peacefully.', 'Они мирно разрешили конфликт.'],
  ['seek', 'искать, обращаться (за помощью)', 'v', 'You should *seek* professional help.', 'Вам стоит обратиться за профессиональной помощью.', { note: 'seek — sought — sought. A formal word for “look for”.' }],
  ['tackle', 'браться за (проблему)', 'v', 'We need to *tackle* the problem together.', 'Нам нужно вместе взяться за эту проблему.'],
  ['trigger', 'вызывать, провоцировать', 'v', 'Loud noises can *trigger* his anxiety.', 'Громкие звуки могут вызывать у него тревогу.'],
  ['influence', 'влиять', 'v', 'Your childhood *influences* who you become.', 'Детство влияет на то, кем вы становитесь.', { note: 'influence someone — no preposition; but have an influence ON someone.' }],
  ['manipulate', 'манипулировать', 'v', 'He tries to *manipulate* people to get what he wants.', 'Он пытается манипулировать людьми, чтобы получить своё.'],
  // Frequent nouns
  ['anxiety', 'тревога, тревожность', 'n', 'Many people suffer from *anxiety*.', 'Многие страдают от тревожности.'],
  ['boundary', 'граница (личная)', 'n', 'It’s healthy to set *boundaries* with your family.', 'Устанавливать границы с семьёй полезно.', { note: 'set boundaries.' }],
  ['empathy', 'эмпатия, сопереживание', 'n', 'A good counsellor shows *empathy*.', 'Хороший консультант проявляет эмпатию.'],
  ['resilience', 'стойкость, жизнестойкость', 'n', 'Sport helps children build *resilience*.', 'Спорт помогает детям развить стойкость.'],
  ['self-esteem', 'самооценка', 'n', 'Constant criticism can damage a child’s *self-esteem*.', 'Постоянная критика может подорвать самооценку ребёнка.'],
  ['trauma', 'травма (психологическая)', 'n', 'Talking about the *trauma* was the first step.', 'Первым шагом стал разговор о травме.'],
  ['burnout', 'выгорание', 'n', 'Working without breaks leads to *burnout*.', 'Работа без перерывов приводит к выгоранию.'],
  ['grief', 'горе', 'n', '*Grief* takes time.', 'Горе требует времени.'],
  ['guilt', 'чувство вины', 'n', 'She felt a lot of *guilt* after the argument.', 'После ссоры она испытывала сильное чувство вины.'],
  ['shame', 'стыд', 'n', 'There’s no *shame* in asking for help.', 'Нет ничего постыдного в том, чтобы попросить о помощи.'],
  ['therapy', 'терапия', 'n', 'She has been in *therapy* for a year.', 'Она ходит на терапию уже год.'],
  ['therapist', 'психотерапевт', 'n', 'My *therapist* helped me a lot.', 'Мой психотерапевт мне очень помог.'],
  ['counsellor', 'консультант, психолог', 'n', 'The school *counsellor* is available every day.', 'Школьный психолог работает каждый день.', { alt: ['counselor'] }],
  ['session', 'сеанс, встреча', 'n', 'Our next *session* is on Tuesday.', 'Наша следующая встреча во вторник.'],
  ['insight', 'понимание, осознание', 'n', 'The session gave me new *insight* into my behaviour.', 'Сеанс помог мне по-новому понять своё поведение.'],
  ['wellbeing', 'благополучие, самочувствие', 'n', 'Sleep is essential for your *wellbeing*.', 'Сон необходим для хорошего самочувствия.', { alt: ['well-being'] }],
  ['mindset', 'образ мышления, настрой', 'n', 'Try to change your *mindset*.', 'Попробуйте изменить свой образ мышления.'],
  ['commitment', 'обязательство; преданность', 'n', 'Marriage is a big *commitment*.', 'Брак — это серьёзное обязательство.'],
  ['attachment', 'привязанность', 'n', 'Babies form an *attachment* to their parents.', 'У младенцев формируется привязанность к родителям.'],
  ['loyalty', 'верность, преданность', 'n', 'I value *loyalty* in a friend.', 'Я ценю верность в друге.'],
  ['jealousy', 'ревность, зависть', 'n', '*Jealousy* can destroy a relationship.', 'Ревность может разрушить отношения.'],
  ['conflict', 'конфликт', 'n', 'They avoid *conflict* at all costs.', 'Они любой ценой избегают конфликтов.'],
  ['tension', 'напряжение', 'n', 'There was a lot of *tension* in the room.', 'В комнате царило сильное напряжение.'],
  ['perspective', 'точка зрения, взгляд', 'n', 'Try to see it from her *perspective*.', 'Попробуй посмотреть на это с её точки зрения.'],
  ['aspect', 'аспект, сторона', 'n', 'Money affects every *aspect* of our lives.', 'Деньги влияют на все стороны нашей жизни.'],
  ['circumstance', 'обстоятельство', 'n', 'Under the *circumstances*, you did your best.', 'В тех обстоятельствах ты сделал всё, что мог.'],
  ['criticism', 'критика', 'n', 'She doesn’t take *criticism* well.', 'Она плохо воспринимает критику.'],
  ['impression', 'впечатление', 'n', 'He made a good *impression* on her parents.', 'Он произвёл хорошее впечатление на её родителей.', { note: 'make an impression ON someone.', rule: 'make-do' }],
  ['strategy', 'стратегия', 'n', 'Breathing slowly is a simple coping *strategy*.', 'Медленное дыхание — простая стратегия, чтобы справиться со стрессом.'],
  ['tendency', 'склонность', 'n', 'He has a *tendency* to worry too much.', 'Он склонен слишком много беспокоиться.'],
  ['factor', 'фактор', 'n', 'Stress is a major *factor* in heart disease.', 'Стресс — важный фактор сердечных заболеваний.'],
  ['debate', 'дискуссия, спор', 'n', 'There’s a lot of *debate* about this issue.', 'Об этом вопросе много спорят.'],
  ['isolation', 'изоляция, одиночество', 'n', '*Isolation* can lead to depression.', 'Изоляция может привести к депрессии.'],
  ['depression', 'депрессия', 'n', '*Depression* is a common illness.', 'Депрессия — распространённое заболевание.'],
  // Frequent adjectives
  ['overwhelmed', 'перегруженный, подавленный', 'adj', 'I feel *overwhelmed* by all the work.', 'Меня захлёстывает от количества работы.', { rule: 'ed-ing' }],
  ['supportive', 'поддерживающий', 'adj', 'My partner is very *supportive*.', 'Мой партнёр очень меня поддерживает.'],
  ['judgemental', 'осуждающий', 'adj', 'Try not to be *judgemental*.', 'Старайся не осуждать.', { alt: ['judgmental'] }],
  ['confidential', 'конфиденциальный', 'adj', 'Everything you say here is *confidential*.', 'Всё, что вы здесь говорите, конфиденциально.'],
  ['appropriate', 'уместный, подходящий', 'adj', 'That joke wasn’t *appropriate*.', 'Эта шутка была неуместной.'],
  ['considerate', 'внимательный (к другим), тактичный', 'adj', 'It was very *considerate* of you to call.', 'Очень внимательно с твоей стороны позвонить.'],
  ['consistent', 'последовательный, постоянный', 'adj', 'Children need *consistent* rules.', 'Детям нужны последовательные правила.'],
  ['desperate', 'отчаявшийся; отчаянный', 'adj', 'He was *desperate* for help.', 'Он отчаянно нуждался в помощи.'],
  ['eager', 'жаждущий, полный желания', 'adj', 'She’s *eager* to learn.', 'Она очень хочет учиться.'],
  ['essential', 'необходимый', 'adj', 'Sleep is *essential* for good health.', 'Сон необходим для хорошего здоровья.'],
  ['gentle', 'мягкий, нежный', 'adj', 'Be *gentle* with yourself.', 'Будь к себе мягче.'],
  ['isolated', 'изолированный, одинокий', 'adj', 'After the move, she felt *isolated*.', 'После переезда она чувствовала себя одинокой.'],
  ['mature', 'зрелый', 'adj', 'He’s very *mature* for his age.', 'Он очень зрелый для своего возраста.'],
  ['reasonable', 'разумный, приемлемый', 'adj', 'That sounds like a *reasonable* price.', 'Это звучит как разумная цена.'],
  ['sincere', 'искренний', 'adj', 'Please accept my *sincere* apologies.', 'Пожалуйста, примите мои искренние извинения.'],
  ['stubborn', 'упрямый', 'adj', 'Don’t be so *stubborn*!', 'Не будь таким упрямым!'],
  ['tense', 'напряжённый', 'adj', 'The atmosphere at dinner was *tense*.', 'За ужином царила напряжённая атмосфера.'],
  ['thoughtful', 'заботливый; задумчивый', 'adj', 'What a *thoughtful* gift!', 'Какой продуманный подарок!'],
  ['vague', 'расплывчатый, неясный', 'adj', 'His answer was very *vague*.', 'Его ответ был очень расплывчатым.'],
  ['vital', 'жизненно важный', 'adj', 'It’s *vital* that you take this medicine.', 'Очень важно, чтобы вы принимали это лекарство.'],
  ['aggressive', 'агрессивный', 'adj', 'He becomes *aggressive* when he drinks.', 'Он становится агрессивным, когда пьёт.'],
  ['dependent', 'зависимый', 'adj', 'She’s financially *dependent* on her parents.', 'Она финансово зависит от родителей.', { note: 'dependent ON.', rule: 'dep-prep' }],
  ['insecure', 'неуверенный в себе', 'adj', 'He feels *insecure* about his appearance.', 'Он не уверен в своей внешности.'],
  ['resilient', 'стойкий, жизнестойкий', 'adj', 'Children are often more *resilient* than we think.', 'Дети часто стойче, чем мы думаем.'],
  ['harmful', 'вредный', 'adj', 'Stress can be *harmful* to your health.', 'Стресс может вредить здоровью.'],
  ['mental', 'психический, умственный', 'adj', 'Exercise is good for your *mental* health.', 'Физические упражнения полезны для психического здоровья.'],
  // Linking words
  ['whereas', 'тогда как', 'conj', 'I love the sea, *whereas* my husband prefers the mountains.', 'Я люблю море, тогда как муж предпочитает горы.'],
  ['nevertheless', 'тем не менее', 'adv', 'It was hard. *Nevertheless*, we finished on time.', 'Было трудно. Тем не менее мы закончили вовремя.'],
  ['furthermore', 'более того', 'adv', 'The flat is cheap. *Furthermore*, it’s close to work.', 'Квартира дешёвая. Более того, она рядом с работой.'],
  ['therefore', 'поэтому, следовательно', 'adv', 'He was ill and *therefore* couldn’t come.', 'Он был болен и поэтому не смог прийти.'],
  ['in spite of', 'несмотря на', 'prep', 'They stayed together *in spite of* their problems.', 'Они остались вместе, несмотря на проблемы.', { note: 'in spite of = despite. Both take a noun or -ing.' }],
];

export const WORDS_B2 = buildVocab('B2', 'word', ROWS);
