import { buildVocab, type Row } from './build';

const ROWS: Row[] = [
  ['afford', 'позволить себе (по деньгам, времени)', 'v', 'I can’t *afford* a new phone right now.', 'Сейчас я не могу позволить себе новый телефон.', { note: 'afford + to do: We can’t afford to wait.', rule: 'verb-patterns' }],
  ['borrow', 'брать взаймы, одалживать (у кого-то)', 'v', 'Can I *borrow* your pen for a minute?', 'Можно одолжить твою ручку на минутку?', { note: 'borrow something FROM someone (you take it); lend something TO someone (you give it).' }],
  ['lend', 'давать взаймы, одалживать (кому-то)', 'v', 'Could you *lend* me some money until Friday?', 'Можешь одолжить мне денег до пятницы?', { note: 'lend — lent — lent. Don’t mix it up with borrow (to take).' }],
  ['receipt', 'чек, квитанция', 'n', 'Keep the *receipt* in case you want to return it.', 'Сохраните чек на случай, если захотите вернуть покупку.', { note: 'The p is silent: [rɪˈsiːt].' }],
  ['journey', 'поездка, путь (дорога)', 'n', 'The *journey* to work takes about forty minutes.', 'Дорога на работу занимает около сорока минут.', { note: 'journey = the travelling itself; trip = the whole visit (going, staying and coming back).' }],
  ['improve', 'улучшать(ся)', 'v', 'I want to *improve* my speaking skills.', 'Я хочу улучшить разговорные навыки.'],
  ['advice', 'совет, советы', 'n', 'Can you give me some *advice* about renting a flat?', 'Можешь дать мне совет насчёт аренды квартиры?', { note: 'Uncountable: some advice, a piece of advice (not an advice).', rule: 'countable' }],
  ['suggest', 'предлагать (идею), советовать', 'v', 'She *suggested* going to the cinema.', 'Она предложила пойти в кино.', { note: 'suggest + -ing or suggest that…; never suggest me to do.', rule: 'verb-patterns' }],
  ['appointment', 'встреча, запись (к врачу)', 'n', 'I have a dentist *appointment* at three.', 'В три у меня запись к стоматологу.', { note: 'make an appointment = book a time (with a doctor, etc.).' }],
  ['available', 'доступный, свободный', 'adj', 'Is this room *available* next weekend?', 'Этот номер свободен на следующих выходных?'],
  ['crowded', 'переполненный (людьми)', 'adj', 'The bus was so *crowded* that I had to stand.', 'Автобус был так переполнен, что пришлось стоять.'],
  ['decide', 'решать, принимать решение', 'v', 'We *decided* to stay at home.', 'Мы решили остаться дома.', { note: 'decide + to do.', rule: 'verb-patterns' }],
  ['disappointed', 'разочарованный', 'adj', 'I was *disappointed* with the film.', 'Фильм меня разочаровал.', { note: 'disappointed = how you feel; disappointing = the film itself.', rule: 'ed-ing' }],
  ['embarrassed', 'смущённый, стыдно, неловко', 'adj', 'I felt *embarrassed* when I forgot her name.', 'Мне было неловко, когда я забыл её имя.', { rule: 'ed-ing' }],
  ['exhausted', 'измотанный, без сил', 'adj', 'After the long flight I was *exhausted*.', 'После долгого перелёта я был без сил.', { rule: 'ed-ing' }],
  ['expensive', 'дорогой', 'adj', 'London is an *expensive* city to live in.', 'Лондон — дорогой город для жизни.'],
  ['familiar', 'знакомый', 'adj', 'Your face looks *familiar*.', 'Ваше лицо кажется знакомым.', { note: 'Not «фамильярный». be familiar with something = know it.', rule: 'false-friends' }],
  ['guess', 'угадывать, догадываться', 'v', '*Guess* who I met yesterday!', 'Угадай, кого я вчера встретил!'],
  ['habit', 'привычка', 'n', 'Biting your nails is a bad *habit*.', 'Грызть ногти — плохая привычка.'],
  ['health', 'здоровье', 'n', 'Walking is good for your *health*.', 'Ходьба полезна для здоровья.'],
  ['however', 'однако', 'adv', 'The hotel was nice. *However*, the food was terrible.', 'Отель был хороший. Однако еда была ужасной.'],
  ['instead', 'вместо (этого)', 'adv', 'Let’s walk *instead* of taking a taxi.', 'Давай пройдёмся пешком вместо того, чтобы брать такси.', { note: 'instead of + -ing or a noun.', rule: 'verb-patterns' }],
  ['invite', 'приглашать', 'v', 'They *invited* us to their wedding.', 'Они пригласили нас на свою свадьбу.', { note: 'invite someone TO something.' }],
  ['knowledge', 'знания', 'n', 'He has a good *knowledge* of history.', 'У него хорошие знания истории.', { note: 'Uncountable: knowledge, no -s.', rule: 'countable' }],
  ['luggage', 'багаж', 'n', 'How much *luggage* are you taking?', 'Сколько багажа ты берёшь?', { note: 'Uncountable: much luggage, a piece of luggage.', rule: 'countable' }],
  ['manage', 'суметь, справиться; управлять', 'v', 'Did you *manage* to finish the report?', 'Тебе удалось закончить отчёт?', { note: 'manage + to do = succeed in doing something difficult.', rule: 'verb-patterns' }],
  ['mention', 'упоминать', 'v', 'She didn’t *mention* her new job.', 'Она не упомянула о своей новой работе.', { note: 'mention something — no about.' }],
  ['neighbour', 'сосед, соседка', 'n', 'Our *neighbours* are very friendly.', 'Наши соседи очень дружелюбные.', { alt: ['neighbor'] }],
  ['opportunity', 'возможность, шанс', 'n', 'This job is a great *opportunity* for me.', 'Эта работа — отличная возможность для меня.'],
  ['persuade', 'убедить, уговорить', 'v', 'I *persuaded* him to see a doctor.', 'Я уговорил его сходить к врачу.', { note: 'persuade someone to do something.' }],
  ['polite', 'вежливый', 'adj', 'It’s *polite* to say thank you.', 'Вежливо говорить «спасибо».'],
  ['prefer', 'предпочитать', 'v', 'I *prefer* tea to coffee.', 'Я предпочитаю чай кофе.', { note: 'prefer A TO B.' }],
  ['queue', 'очередь', 'n', 'There was a long *queue* at the post office.', 'На почте была длинная очередь.', { note: 'In American English: line.' }],
  ['recommend', 'рекомендовать, советовать', 'v', 'Can you *recommend* a good restaurant?', 'Можешь посоветовать хороший ресторан?'],
  ['rent', 'снимать, арендовать; арендная плата', 'v', 'We *rent* a small flat in the city centre.', 'Мы снимаем небольшую квартиру в центре города.'],
  ['reliable', 'надёжный', 'adj', 'My old car is still very *reliable*.', 'Моя старая машина всё ещё очень надёжная.'],
  ['remind', 'напоминать', 'v', '*Remind* me to call my mum tonight.', 'Напомни мне позвонить маме вечером.', { note: 'remind someone to do something; remind someone of something (= make them think of it).' }],
  ['sensible', 'разумный, здравый', 'adj', 'It was a *sensible* decision.', 'Это было разумное решение.', { note: 'Not «чувствительный» — that is sensitive.', rule: 'false-friends' }],
  ['sensitive', 'чувствительный, ранимый', 'adj', 'She’s very *sensitive* to criticism.', 'Она очень болезненно воспринимает критику.'],
  ['spend', 'тратить; проводить (время)', 'v', 'I *spend* too much money on clothes.', 'Я трачу слишком много денег на одежду.', { note: 'spend money/time ON something; spend time doing something.', rule: 'dep-prep' }],
  ['succeed', 'добиться успеха, суметь', 'v', 'She *succeeded* in passing the exam.', 'Ей удалось сдать экзамен.', { note: 'succeed IN + -ing.', rule: 'dep-prep' }],
  ['suitable', 'подходящий', 'adj', 'This film isn’t *suitable* for children.', 'Этот фильм не подходит для детей.'],
  ['traffic', 'дорожное движение, пробки', 'n', 'Sorry I’m late, the *traffic* was terrible.', 'Извини за опоздание, были ужасные пробки.', { note: 'Uncountable. One jam on the road is a traffic jam.', rule: 'countable' }],
  ['unfortunately', 'к сожалению', 'adv', '*Unfortunately*, the museum was closed.', 'К сожалению, музей был закрыт.'],
  ['weather', 'погода', 'n', 'What’s the *weather* like today?', 'Какая сегодня погода?', { note: 'Uncountable: not a weather. What’s the weather like?', rule: 'countable' }],
  ['worried', 'обеспокоенный, волнующийся', 'adj', 'I’m *worried* about my exam.', 'Я волнуюсь из-за экзамена.', { note: 'worried ABOUT.', rule: 'dep-prep' }],
  ['achieve', 'достигать', 'v', 'She *achieved* her goal of running a marathon.', 'Она достигла своей цели — пробежала марафон.'],
  ['argue', 'спорить, ругаться', 'v', 'My brother and I often *argue* about politics.', 'Мы с братом часто спорим о политике.', { note: 'argue WITH someone ABOUT something.' }],
  ['attitude', 'отношение (к чему-то)', 'n', 'He has a positive *attitude* to work.', 'У него позитивное отношение к работе.'],
  ['behave', 'вести себя', 'v', 'The children *behaved* very well today.', 'Дети сегодня вели себя очень хорошо.'],
  ['bill', 'счёт (в ресторане, за услуги)', 'n', 'Could we have the *bill*, please?', 'Можно нам счёт, пожалуйста?', { note: 'In an American restaurant: the check.' }],
  ['complain', 'жаловаться', 'v', 'He always *complains* about the food.', 'Он вечно жалуется на еду.', { note: 'complain ABOUT something, TO someone.', rule: 'dep-prep' }],
  ['convenient', 'удобный (по времени, месту)', 'adj', 'Is Monday *convenient* for you?', 'Вам удобно в понедельник?', { note: 'A soft sofa is comfortable, not convenient.' }],
  ['cancel', 'отменять', 'v', 'Our flight was *cancelled* because of the storm.', 'Наш рейс отменили из-за шторма.', { alt: ['canceled'] }],
  ['customer', 'покупатель, клиент', 'n', 'The shop was full of *customers*.', 'В магазине было полно покупателей.'],
  ['deliver', 'доставлять', 'v', 'They’ll *deliver* the sofa on Tuesday.', 'Диван доставят во вторник.'],
  ['describe', 'описывать', 'v', 'Can you *describe* the man you saw?', 'Можете описать мужчину, которого вы видели?', { note: 'describe something TO someone (not describe me).', rule: 'say-tell' }],
  ['environment', 'окружающая среда; обстановка', 'n', 'We must protect the *environment*.', 'Мы должны защищать окружающую среду.'],
  ['experience', 'опыт; случай, впечатление', 'n', 'Do you have any *experience* of working with children?', 'У вас есть опыт работы с детьми?'],
  ['fault', 'вина', 'n', 'Don’t blame me. It’s not my *fault*!', 'Не вини меня. Это не моя вина!'],
  ['forgive', 'прощать', 'v', 'Please *forgive* me for being late.', 'Пожалуйста, прости, что я опоздал.'],
  ['goal', 'цель', 'n', 'My *goal* is to speak English fluently.', 'Моя цель — свободно говорить по-английски.'],
  ['ignore', 'игнорировать, не обращать внимания', 'v', 'Just *ignore* him, he’s in a bad mood.', 'Просто не обращай на него внимания, он не в духе.'],
  ['lazy', 'ленивый', 'adj', 'I was too *lazy* to cook, so we ordered pizza.', 'Мне было лень готовить, и мы заказали пиццу.'],
  ['lonely', 'одинокий (о чувстве)', 'adj', 'She feels *lonely* since her kids moved out.', 'Ей одиноко с тех пор, как дети съехали.', { note: 'alone = without other people (a fact); lonely = sad because you are alone (a feeling).' }],
  ['nervous', 'нервничающий, волнующийся', 'adj', 'I always get *nervous* before interviews.', 'Я всегда нервничаю перед собеседованиями.'],
  ['offer', 'предлагать (дать или сделать)', 'v', 'He *offered* to help me with my bags.', 'Он предложил помочь мне с сумками.', { note: 'offer + to do. To suggest an idea: suggest.', rule: 'verb-patterns' }],
  ['patient', 'терпеливый; пациент', 'adj', 'Be *patient*, the doctor will see you soon.', 'Потерпите, врач скоро вас примет.'],
  ['proud', 'гордый, гордящийся', 'adj', 'I’m so *proud* of you!', 'Я так тобой горжусь!', { note: 'proud OF.', rule: 'dep-prep' }],
  ['rude', 'грубый, невежливый', 'adj', 'It’s *rude* to interrupt people.', 'Перебивать людей невежливо.'],
  ['several', 'несколько', 'det', 'I’ve been to Paris *several* times.', 'Я был в Париже несколько раз.'],
  ['solve', 'решать (проблему, задачу)', 'v', 'We need to *solve* this problem quickly.', 'Нам нужно быстро решить эту проблему.', { note: 'solve a problem, but decide what to do.' }],
  ['staff', 'персонал, сотрудники', 'n', 'The hotel *staff* were very helpful.', 'Персонал отеля был очень услужливым.'],
  ['tidy', 'аккуратный, прибранный; убирать', 'adj', 'Please keep your room *tidy*.', 'Пожалуйста, поддерживай порядок в комнате.', { note: 'tidy up = make a place clean and neat.' }],
  ['valuable', 'ценный', 'adj', 'Thanks for the *valuable* advice.', 'Спасибо за ценный совет.'],
  ['waste', 'тратить впустую; отходы', 'v', 'Don’t *waste* your time on that.', 'Не трать на это время.'],
  ['wonder', 'интересоваться, задаваться вопросом', 'v', 'I *wonder* what time it is.', 'Интересно, который час.', { note: 'After I wonder, use normal word order: I wonder where she is.', rule: 'questions' }],
  ['abroad', 'за границей, за границу', 'adv', 'Have you ever lived *abroad*?', 'Ты когда-нибудь жил за границей?', { note: 'No preposition: go abroad (not go to abroad).' }],
  ['accommodation', 'жильё, размещение', 'n', 'The price includes *accommodation* and breakfast.', 'В цену входит проживание и завтрак.', { note: 'Uncountable in British English.', rule: 'countable' }],
  ['apologise', 'извиняться', 'v', 'He *apologised* for being late.', 'Он извинился за опоздание.', { alt: ['apologize'], note: 'apologise FOR something, TO someone.', rule: 'dep-prep' }],
  ['brave', 'храбрый', 'adj', 'It was very *brave* of you to say that.', 'С твоей стороны было очень смело это сказать.'],
  ['confident', 'уверенный (в себе)', 'adj', 'I feel more *confident* speaking English now.', 'Теперь я увереннее говорю по-английски.'],
  ['equipment', 'оборудование, снаряжение', 'n', 'Do we need any special *equipment*?', 'Нам нужно какое-то специальное снаряжение?', { note: 'Uncountable: no -s and no an.', rule: 'countable' }],
  ['furniture', 'мебель', 'n', 'We need to buy some new *furniture*.', 'Нам нужно купить новую мебель.', { note: 'Uncountable: a piece of furniture = one item.', rule: 'countable' }],
  ['salary', 'зарплата (оклад)', 'n', 'The job has a good *salary*.', 'На этой работе хорошая зарплата.'],
  ['skill', 'навык, умение', 'n', 'Communication *skills* are important in any job.', 'Навыки общения важны на любой работе.'],
  ['prepare', 'готовить(ся)', 'v', 'I need to *prepare* for tomorrow’s meeting.', 'Мне нужно подготовиться к завтрашней встрече.', { note: 'prepare FOR something.' }],
  ['frightened', 'испуганный', 'adj', 'The child was *frightened* of the dark.', 'Ребёнок боялся темноты.', { note: 'frightened OF.', rule: 'dep-prep' }],
  ['generous', 'щедрый', 'adj', 'It’s very *generous* of you to pay for dinner.', 'Очень щедро с твоей стороны оплатить ужин.'],
  ['honest', 'честный', 'adj', 'To be *honest*, I didn’t like the film.', 'Честно говоря, фильм мне не понравился.', { note: 'The h is silent: an honest man.' }],
  ['mess', 'беспорядок, бардак', 'n', 'Sorry about the *mess*, we’re moving house.', 'Извините за беспорядок, мы переезжаем.'],
  ['noisy', 'шумный', 'adj', 'Our street is very *noisy* at night.', 'Ночью на нашей улице очень шумно.'],
  ['shy', 'застенчивый', 'adj', 'He was too *shy* to ask her to dance.', 'Он был слишком застенчив, чтобы пригласить её на танец.'],
  ['magazine', 'журнал', 'n', 'I read an interesting article in a *magazine*.', 'Я прочитал интересную статью в журнале.', { note: 'Магазин is a shop or a store.', rule: 'false-friends' }],
  // Frequent verbs
  ['accept', 'принимать (предложение, ситуацию)', 'v', 'She *accepted* the job offer.', 'Она приняла предложение о работе.'],
  ['admit', 'признавать', 'v', 'He *admitted* that he was wrong.', 'Он признал, что был неправ.', { note: 'admit + -ing: He admitted taking the money.', rule: 'verb-patterns' }],
  ['avoid', 'избегать', 'v', 'I try to *avoid* eating late.', 'Я стараюсь не есть поздно.', { note: 'avoid + -ing.', rule: 'verb-patterns' }],
  ['blame', 'винить', 'v', 'Don’t *blame* yourself for what happened.', 'Не вини себя в том, что случилось.', { note: 'blame someone FOR something.', rule: 'dep-prep' }],
  ['breathe', 'дышать', 'v', 'Close your eyes and *breathe* slowly.', 'Закройте глаза и дышите медленно.', { note: 'The noun is breath: take a deep breath.' }],
  ['celebrate', 'праздновать', 'v', 'We *celebrated* our anniversary in Paris.', 'Мы отпраздновали годовщину в Париже.'],
  ['compare', 'сравнивать', 'v', 'Stop *comparing* yourself to others.', 'Перестань сравнивать себя с другими.', { note: 'compare A with/to B.' }],
  ['deserve', 'заслуживать', 'v', 'You *deserve* a break.', 'Ты заслуживаешь отдыха.'],
  ['disagree', 'не соглашаться', 'v', 'I *disagree* with you on this.', 'Я с тобой в этом не согласен.', { note: 'A verb, like agree: I disagree (not I am disagree).', rule: 'agree' }],
  ['earn', 'зарабатывать', 'v', 'She *earns* more than her husband.', 'Она зарабатывает больше мужа.'],
  ['expect', 'ожидать', 'v', 'I didn’t *expect* you to come.', 'Я не ожидал, что ты придёшь.', { note: 'expect someone to do something.' }],
  ['express', 'выражать', 'v', 'It’s important to *express* your feelings.', 'Важно выражать свои чувства.'],
  ['fail', 'провалить; не суметь', 'v', 'He *failed* his driving test.', 'Он провалил экзамен по вождению.', { note: 'fail to do = not manage to do.' }],
  ['hide', 'прятать(ся), скрывать', 'v', 'She tried to *hide* her disappointment.', 'Она пыталась скрыть разочарование.'],
  ['hurt', 'ранить, обидеть; болеть', 'v', 'I didn’t mean to *hurt* your feelings.', 'Я не хотел тебя обидеть.', { note: 'hurt — hurt — hurt. Also about pain: My back hurts.' }],
  ['include', 'включать (в себя)', 'v', 'The price *includes* breakfast.', 'В цену входит завтрак.'],
  ['increase', 'увеличивать(ся)', 'v', 'The number of students has *increased*.', 'Число студентов увеличилось.'],
  ['notice', 'замечать', 'v', 'Did you *notice* anything strange?', 'Ты заметил что-нибудь странное?'],
  ['pretend', 'притворяться', 'v', 'He *pretended* to be asleep.', 'Он притворился спящим.', { note: 'pretend + to do.', rule: 'verb-patterns' }],
  ['promise', 'обещать', 'v', 'I *promise* I won’t tell anyone.', 'Обещаю, что никому не скажу.', { note: 'promise + to do.', rule: 'verb-patterns' }],
  ['protect', 'защищать', 'v', 'Parents want to *protect* their children.', 'Родители хотят защищать своих детей.'],
  ['realise', 'осознавать, понимать', 'v', 'I *realised* I had left my phone at home.', 'Я понял, что оставил телефон дома.', { alt: ['realize'] }],
  ['reduce', 'уменьшать, снижать', 'v', 'Exercise can *reduce* stress.', 'Физические упражнения могут снизить стресс.'],
  ['refuse', 'отказываться', 'v', 'She *refused* to answer the question.', 'Она отказалась отвечать на вопрос.', { note: 'refuse + to do.', rule: 'verb-patterns' }],
  ['regret', 'сожалеть', 'v', 'I *regret* not telling her the truth.', 'Жалею, что не сказал ей правду.', { note: 'regret + -ing for things in the past.' }],
  ['reply', 'отвечать', 'v', 'He never *replied* to my message.', 'Он так и не ответил на моё сообщение.', { note: 'reply TO something.', rule: 'dep-prep' }],
  ['rush', 'торопиться, спешить', 'v', 'There’s no need to *rush*.', 'Торопиться некуда.'],
  ['share', 'делиться', 'v', 'Thank you for *sharing* your story.', 'Спасибо, что поделились своей историей.', { note: 'share something WITH someone.' }],
  ['support', 'поддерживать; поддержка', 'v', 'My family has always *supported* me.', 'Семья всегда меня поддерживала.', { note: 'Also a noun: Thank you for your support.' }],
  ['survive', 'выжить, пережить', 'v', 'Only two people *survived* the crash.', 'Только два человека выжили в аварии.'],
  ['trust', 'доверять; доверие', 'v', 'I *trust* you completely.', 'Я тебе полностью доверяю.', { note: 'trust someone — no preposition. Also a noun: trust is important.' }],
  ['warn', 'предупреждать', 'v', 'I *warned* you about the traffic!', 'Я же предупреждал тебя о пробках!'],
  ['whisper', 'шептать', 'v', 'She *whispered* something in his ear.', 'Она что-то прошептала ему на ухо.'],
  ['cheat', 'обманывать, жульничать', 'v', 'He *cheated* in the exam.', 'Он списывал на экзамене.', { note: 'cheat on someone = be unfaithful to your partner.' }],
  ['suffer', 'страдать', 'v', 'Many people *suffer* from back pain.', 'Многие страдают от боли в спине.', { note: 'suffer FROM something.', rule: 'dep-prep' }],
  ['respect', 'уважать; уважение', 'v', 'I *respect* your decision.', 'Я уважаю твоё решение.'],
  ['seem', 'казаться', 'v', 'You *seem* tired today.', 'Ты сегодня выглядишь уставшим.', { note: 'seem + adjective, or seem to do: She seems to like you.' }],
  ['mind', 'возражать, быть против', 'v', 'Do you *mind* if I open the window?', 'Вы не против, если я открою окно?', { note: 'mind + -ing: Would you mind waiting?', rule: 'verb-patterns' }],
  ['recognise', 'узнавать (кого-то)', 'v', 'I didn’t *recognise* you with short hair!', 'Я тебя не узнал с короткой стрижкой!', { alt: ['recognize'] }],
  // Frequent nouns
  ['ability', 'способность', 'n', 'She has the *ability* to stay calm under pressure.', 'У неё есть способность сохранять спокойствие под давлением.'],
  ['advantage', 'преимущество', 'n', 'One *advantage* of living here is the view.', 'Одно из преимуществ жизни здесь — вид.'],
  ['aim', 'цель', 'n', 'The *aim* of this exercise is to relax.', 'Цель этого упражнения — расслабиться.'],
  ['amount', 'количество, сумма', 'n', 'A large *amount* of money was stolen.', 'Была украдена большая сумма денег.', { note: 'amount + uncountable nouns; number + countable nouns.', rule: 'countable' }],
  ['behaviour', 'поведение', 'n', 'His *behaviour* at the party was rude.', 'Его поведение на вечеринке было грубым.', { alt: ['behavior'] }],
  ['belief', 'убеждение, вера', 'n', 'We all have different *beliefs*.', 'У нас у всех разные убеждения.'],
  ['choice', 'выбор', 'n', 'You made the right *choice*.', 'Ты сделал правильный выбор.', { note: 'make a choice (not do).', rule: 'make-do' }],
  ['confidence', 'уверенность (в себе)', 'n', 'She lost her *confidence* after the accident.', 'После аварии она потеряла уверенность в себе.'],
  ['conversation', 'разговор', 'n', 'We had a long *conversation* about the future.', 'У нас был долгий разговор о будущем.', { note: 'have a conversation.' }],
  ['decision', 'решение', 'n', 'It was a difficult *decision*.', 'Это было трудное решение.', { note: 'make a decision.', rule: 'make-do' }],
  ['effort', 'усилие', 'n', 'Learning a language takes a lot of *effort*.', 'Изучение языка требует больших усилий.', { note: 'make an effort.', rule: 'make-do' }],
  ['emotion', 'эмоция', 'n', 'He finds it hard to show his *emotions*.', 'Ему трудно показывать свои эмоции.'],
  ['feeling', 'чувство', 'n', 'I have a *feeling* that something is wrong.', 'У меня такое чувство, что что-то не так.'],
  ['fear', 'страх', 'n', 'She talked about her *fear* of failure.', 'Она рассказала о своём страхе неудачи.', { note: 'fear OF something.' }],
  ['freedom', 'свобода', 'n', 'Teenagers want more *freedom*.', 'Подростки хотят больше свободы.'],
  ['friendship', 'дружба', 'n', 'Their *friendship* lasted for forty years.', 'Их дружба длилась сорок лет.'],
  ['memory', 'память; воспоминание', 'n', 'I have happy *memories* of my childhood.', 'У меня счастливые воспоминания о детстве.'],
  ['mood', 'настроение', 'n', 'You’re in a good *mood* today!', 'Ты сегодня в хорошем настроении!', { note: 'be in a good/bad mood.' }],
  ['opinion', 'мнение', 'n', 'In my *opinion*, it’s too expensive.', 'По-моему, это слишком дорого.', { note: 'in my opinion (not on my opinion).' }],
  ['pain', 'боль', 'n', 'I’ve got a *pain* in my back.', 'У меня болит спина.'],
  ['patience', 'терпение', 'n', 'Thank you for your *patience*.', 'Спасибо за ваше терпение.'],
  ['personality', 'характер, личность', 'n', 'She has a strong *personality*.', 'У неё сильный характер.'],
  ['pressure', 'давление', 'n', 'I work well under *pressure*.', 'Я хорошо работаю под давлением.'],
  ['relationship', 'отношения', 'n', 'They have a very close *relationship*.', 'У них очень близкие отношения.', { note: 'a relationship WITH someone.' }],
  ['responsibility', 'ответственность', 'n', 'Taking care of a dog is a big *responsibility*.', 'Забота о собаке — большая ответственность.'],
  ['risk', 'риск', 'n', 'Smoking increases the *risk* of heart disease.', 'Курение повышает риск сердечных заболеваний.', { note: 'take a risk.' }],
  ['secret', 'секрет, тайна', 'n', 'Can you keep a *secret*?', 'Ты умеешь хранить секреты?'],
  ['stress', 'стресс', 'n', 'Too much *stress* is bad for your health.', 'Слишком сильный стресс вреден для здоровья.'],
  ['success', 'успех', 'n', 'The party was a great *success*.', 'Вечеринка имела огромный успех.', { note: 'Adjective: successful. Verb: succeed.' }],
  ['truth', 'правда', 'n', 'Tell me the *truth*.', 'Скажи мне правду.', { note: 'tell the truth (not say the truth).', rule: 'say-tell' }],
  ['strength', 'сила; сильная сторона', 'n', 'Patience is one of her *strengths*.', 'Терпение — одна из её сильных сторон.'],
  ['weakness', 'слабость; слабое место', 'n', 'Chocolate is my *weakness*.', 'Шоколад — моя слабость.'],
  ['anger', 'гнев, злость', 'n', 'He couldn’t control his *anger*.', 'Он не мог контролировать свою злость.'],
  ['childhood', 'детство', 'n', 'She had a happy *childhood*.', 'У неё было счастливое детство.'],
  ['partner', 'партнёр, партнёрша', 'n', 'Do you live with your *partner*?', 'Вы живёте с партнёром?'],
  ['couple', 'пара', 'n', 'They’re a lovely *couple*.', 'Они прекрасная пара.', { note: 'a couple of = two or a few.' }],
  ['marriage', 'брак', 'n', 'They have a happy *marriage*.', 'У них счастливый брак.'],
  ['divorce', 'развод', 'n', 'Her parents got a *divorce* when she was six.', 'Её родители развелись, когда ей было шесть.', { note: 'get a divorce / get divorced.' }],
  ['value', 'ценность', 'n', 'Honesty is an important *value* for me.', 'Честность — важная для меня ценность.'],
  ['view', 'взгляд, мнение; вид', 'n', 'We have different *views* on education.', 'У нас разные взгляды на образование.'],
  ['attention', 'внимание', 'n', 'Can I have your *attention*, please?', 'Прошу внимания!', { note: 'pay attention TO something.' }],
  // Frequent adjectives
  ['annoyed', 'раздражённый', 'adj', 'I was *annoyed* that he was late again.', 'Меня раздражало, что он снова опоздал.', { rule: 'ed-ing' }],
  ['ashamed', 'пристыжённый; стыдно', 'adj', 'I’m *ashamed* of what I said.', 'Мне стыдно за то, что я сказал.', { note: 'ashamed OF.', rule: 'dep-prep' }],
  ['aware', 'осознающий, знающий', 'adj', 'Are you *aware* of the risks?', 'Вы осознаёте риски?', { note: 'be aware OF something.' }],
  ['calm', 'спокойный', 'adj', 'Try to stay *calm*.', 'Постарайся сохранять спокойствие.'],
  ['cheerful', 'весёлый, жизнерадостный', 'adj', 'She’s always *cheerful* in the morning.', 'По утрам она всегда жизнерадостная.'],
  ['curious', 'любопытный', 'adj', 'Children are naturally *curious*.', 'Дети от природы любопытны.'],
  ['depressed', 'подавленный', 'adj', 'He felt *depressed* after losing his job.', 'После потери работы он был подавлен.', { rule: 'ed-ing' }],
  ['emotional', 'эмоциональный; трогательный', 'adj', 'It was a very *emotional* moment.', 'Это был очень трогательный момент.'],
  ['fair', 'справедливый, честный', 'adj', 'It’s not *fair*!', 'Это нечестно!'],
  ['guilty', 'виноватый', 'adj', 'I feel *guilty* about not calling my mum.', 'Мне стыдно, что я не звоню маме.', { note: 'feel guilty ABOUT something.' }],
  ['jealous', 'ревнивый; завидующий', 'adj', 'He gets *jealous* when she talks to other men.', 'Он ревнует, когда она разговаривает с другими мужчинами.', { note: 'jealous OF someone.' }],
  ['miserable', 'несчастный', 'adj', 'I was *miserable* in that job.', 'Я был несчастен на той работе.'],
  ['negative', 'негативный, отрицательный', 'adj', 'Try not to focus on *negative* thoughts.', 'Старайтесь не зацикливаться на негативных мыслях.'],
  ['positive', 'позитивный, положительный', 'adj', 'She has a very *positive* attitude.', 'У неё очень позитивный настрой.'],
  ['relaxed', 'расслабленный', 'adj', 'You look very *relaxed*.', 'Ты выглядишь очень расслабленным.', { rule: 'ed-ing' }],
  ['relieved', 'испытывающий облегчение', 'adj', 'I was so *relieved* when the test was over.', 'Я почувствовал такое облегчение, когда тест закончился.'],
  ['selfish', 'эгоистичный', 'adj', 'It was *selfish* of him to leave without saying goodbye.', 'Было эгоистично с его стороны уйти не попрощавшись.'],
  ['shocked', 'потрясённый', 'adj', 'We were *shocked* by the news.', 'Новость нас потрясла.', { rule: 'ed-ing' }],
  ['stressed', 'в стрессе, напряжённый', 'adj', 'I’m really *stressed* about work.', 'У меня сильный стресс из-за работы.'],
  ['upset', 'расстроенный', 'adj', 'She was *upset* that nobody remembered her birthday.', 'Она расстроилась, что никто не вспомнил о её дне рождения.', { note: 'upset ABOUT something.' }],
  ['independent', 'независимый, самостоятельный', 'adj', 'She’s very *independent* for her age.', 'Она очень самостоятельная для своего возраста.'],
  ['romantic', 'романтичный', 'adj', 'He planned a *romantic* dinner.', 'Он устроил романтический ужин.'],
  ['confused', 'растерянный, сбитый с толку', 'adj', 'I’m *confused*. Can you explain again?', 'Я запутался. Можешь объяснить ещё раз?', { rule: 'ed-ing' }],
  ['scared', 'испуганный', 'adj', 'I’m *scared* of flying.', 'Я боюсь летать.', { note: 'scared OF.', rule: 'dep-prep' }],
  ['grateful', 'благодарный', 'adj', 'I’m really *grateful* for your help.', 'Я очень благодарен за твою помощь.', { note: 'grateful FOR something, TO someone.' }],
  // Linking words
  ['although', 'хотя', 'conj', '*Although* it was raining, we went for a walk.', 'Хотя шёл дождь, мы пошли гулять.'],
  ['anyway', 'всё равно; в любом случае', 'adv', 'It’s expensive, but I’ll buy it *anyway*.', 'Это дорого, но я всё равно куплю.'],
  ['especially', 'особенно', 'adv', 'I love fruit, *especially* apples.', 'Я люблю фрукты, особенно яблоки.'],
  ['recently', 'недавно, в последнее время', 'adv', 'Have you seen Tom *recently*?', 'Ты видел Тома в последнее время?', { rule: 'present-perfect' }],
  ['suddenly', 'вдруг, внезапно', 'adv', '*Suddenly*, the lights went out.', 'Вдруг погас свет.'],
  ['despite', 'несмотря на', 'prep', '*Despite* the rain, we had a great time.', 'Несмотря на дождь, мы отлично провели время.', { note: 'despite + noun or -ing — no “of”.' }],
  ['otherwise', 'иначе, в противном случае', 'adv', 'Hurry up, *otherwise* we’ll miss the train.', 'Поторопись, иначе опоздаем на поезд.'],
  ['definitely', 'определённо, точно', 'adv', 'I’ll *definitely* call you tomorrow.', 'Я обязательно позвоню тебе завтра.'],
  ['basically', 'по сути', 'adv', '*Basically*, we need more time.', 'По сути, нам нужно больше времени.'],
];

export const WORDS_B1 = buildVocab('B1', 'word', ROWS);
