import { buildVocab, type Row } from './build';

const ROWS: Row[] = [
  ['afford', 'позволить себе (по деньгам, времени)', 'v', 'I can’t *afford* a new phone right now.', 'Сейчас я не могу позволить себе новый телефон.', { note: 'afford + to do: We can’t afford to wait.', rule: 'verb-patterns' }],
  ['borrow', 'брать взаймы, одалживать (у кого-то)', 'v', 'Can I *borrow* your pen for a minute?', 'Можно одолжить твою ручку на минутку?', { note: 'borrow FROM someone — брать у кого-то; lend TO someone — давать кому-то.' }],
  ['lend', 'давать взаймы, одалживать (кому-то)', 'v', 'Could you *lend* me some money until Friday?', 'Можешь одолжить мне денег до пятницы?', { note: 'lend — lent — lent. Не путайте с borrow (брать).' }],
  ['receipt', 'чек, квитанция', 'n', 'Keep the *receipt* in case you want to return it.', 'Сохраните чек на случай, если захотите вернуть покупку.', { note: 'Буква p не читается: [rɪˈsiːt].' }],
  ['journey', 'поездка, путь (дорога)', 'n', 'The *journey* to work takes about forty minutes.', 'Дорога на работу занимает около сорока минут.', { note: 'journey — сам путь; trip — поездка целиком (туда, там и обратно).' }],
  ['improve', 'улучшать(ся)', 'v', 'I want to *improve* my speaking skills.', 'Я хочу улучшить разговорные навыки.'],
  ['advice', 'совет, советы', 'n', 'Can you give me some *advice* about renting a flat?', 'Можешь дать мне совет насчёт аренды квартиры?', { note: 'Неисчисляемое: some advice, a piece of advice (не an advice).', rule: 'countable' }],
  ['suggest', 'предлагать (идею), советовать', 'v', 'She *suggested* going to the cinema.', 'Она предложила пойти в кино.', { note: 'suggest + -ing или suggest that…; нельзя suggest me to do.', rule: 'verb-patterns' }],
  ['appointment', 'встреча, запись (к врачу)', 'n', 'I have a dentist *appointment* at three.', 'В три у меня запись к стоматологу.', { note: 'make an appointment — записаться.' }],
  ['available', 'доступный, свободный', 'adj', 'Is this room *available* next weekend?', 'Этот номер свободен на следующих выходных?'],
  ['crowded', 'переполненный (людьми)', 'adj', 'The bus was so *crowded* that I had to stand.', 'Автобус был так переполнен, что пришлось стоять.'],
  ['decide', 'решать, принимать решение', 'v', 'We *decided* to stay at home.', 'Мы решили остаться дома.', { note: 'decide + to do.', rule: 'verb-patterns' }],
  ['disappointed', 'разочарованный', 'adj', 'I was *disappointed* with the film.', 'Фильм меня разочаровал.', { note: 'disappointed — чувство человека; disappointing — сам фильм.', rule: 'ed-ing' }],
  ['embarrassed', 'смущённый, стыдно, неловко', 'adj', 'I felt *embarrassed* when I forgot her name.', 'Мне было неловко, когда я забыл её имя.', { rule: 'ed-ing' }],
  ['exhausted', 'измотанный, без сил', 'adj', 'After the long flight I was *exhausted*.', 'После долгого перелёта я был без сил.', { rule: 'ed-ing' }],
  ['expensive', 'дорогой', 'adj', 'London is an *expensive* city to live in.', 'Лондон — дорогой город для жизни.'],
  ['familiar', 'знакомый', 'adj', 'Your face looks *familiar*.', 'Ваше лицо кажется знакомым.', { note: 'Не «фамильярный». be familiar with — быть знакомым с чем-то.', rule: 'false-friends' }],
  ['guess', 'угадывать, догадываться', 'v', '*Guess* who I met yesterday!', 'Угадай, кого я вчера встретил!'],
  ['habit', 'привычка', 'n', 'Biting your nails is a bad *habit*.', 'Грызть ногти — плохая привычка.'],
  ['health', 'здоровье', 'n', 'Walking is good for your *health*.', 'Ходьба полезна для здоровья.'],
  ['however', 'однако', 'adv', 'The hotel was nice. *However*, the food was terrible.', 'Отель был хороший. Однако еда была ужасной.'],
  ['instead', 'вместо (этого)', 'adv', 'Let’s walk *instead* of taking a taxi.', 'Давай пройдёмся пешком вместо того, чтобы брать такси.', { note: 'instead of + -ing или существительное.', rule: 'verb-patterns' }],
  ['invite', 'приглашать', 'v', 'They *invited* us to their wedding.', 'Они пригласили нас на свою свадьбу.', { note: 'invite someone TO something.' }],
  ['knowledge', 'знания', 'n', 'He has a good *knowledge* of history.', 'У него хорошие знания истории.', { note: 'Неисчисляемое: knowledge, без -s.', rule: 'countable' }],
  ['luggage', 'багаж', 'n', 'How much *luggage* are you taking?', 'Сколько багажа ты берёшь?', { note: 'Неисчисляемое: much luggage, a piece of luggage.', rule: 'countable' }],
  ['manage', 'суметь, справиться; управлять', 'v', 'Did you *manage* to finish the report?', 'Тебе удалось закончить отчёт?', { note: 'manage + to do = суметь сделать.', rule: 'verb-patterns' }],
  ['mention', 'упоминать', 'v', 'She didn’t *mention* her new job.', 'Она не упомянула о своей новой работе.', { note: 'mention something — без about.' }],
  ['neighbour', 'сосед, соседка', 'n', 'Our *neighbours* are very friendly.', 'Наши соседи очень дружелюбные.', { alt: ['neighbor'] }],
  ['opportunity', 'возможность, шанс', 'n', 'This job is a great *opportunity* for me.', 'Эта работа — отличная возможность для меня.'],
  ['persuade', 'убедить, уговорить', 'v', 'I *persuaded* him to see a doctor.', 'Я уговорил его сходить к врачу.', { note: 'persuade someone to do something.' }],
  ['polite', 'вежливый', 'adj', 'It’s *polite* to say thank you.', 'Вежливо говорить «спасибо».'],
  ['prefer', 'предпочитать', 'v', 'I *prefer* tea to coffee.', 'Я предпочитаю чай кофе.', { note: 'prefer A TO B.' }],
  ['queue', 'очередь', 'n', 'There was a long *queue* at the post office.', 'На почте была длинная очередь.', { note: 'В американском английском — line.' }],
  ['recommend', 'рекомендовать, советовать', 'v', 'Can you *recommend* a good restaurant?', 'Можешь посоветовать хороший ресторан?'],
  ['rent', 'снимать, арендовать; арендная плата', 'v', 'We *rent* a small flat in the city centre.', 'Мы снимаем небольшую квартиру в центре города.'],
  ['reliable', 'надёжный', 'adj', 'My old car is still very *reliable*.', 'Моя старая машина всё ещё очень надёжная.'],
  ['remind', 'напоминать', 'v', '*Remind* me to call my mum tonight.', 'Напомни мне позвонить маме вечером.', { note: 'remind someone to do; remind someone of something — напоминать кого-то/что-то.' }],
  ['sensible', 'разумный, здравый', 'adj', 'It was a *sensible* decision.', 'Это было разумное решение.', { note: 'Не «чувствительный» — это sensitive.', rule: 'false-friends' }],
  ['sensitive', 'чувствительный, ранимый', 'adj', 'She’s very *sensitive* to criticism.', 'Она очень болезненно воспринимает критику.'],
  ['spend', 'тратить; проводить (время)', 'v', 'I *spend* too much money on clothes.', 'Я трачу слишком много денег на одежду.', { note: 'spend money/time ON something; spend time doing something.', rule: 'dep-prep' }],
  ['succeed', 'добиться успеха, суметь', 'v', 'She *succeeded* in passing the exam.', 'Ей удалось сдать экзамен.', { note: 'succeed IN + -ing.', rule: 'dep-prep' }],
  ['suitable', 'подходящий', 'adj', 'This film isn’t *suitable* for children.', 'Этот фильм не подходит для детей.'],
  ['traffic', 'дорожное движение, пробки', 'n', 'Sorry I’m late, the *traffic* was terrible.', 'Извини за опоздание, были ужасные пробки.', { note: 'Неисчисляемое. Одна пробка — a traffic jam.', rule: 'countable' }],
  ['unfortunately', 'к сожалению', 'adv', '*Unfortunately*, the museum was closed.', 'К сожалению, музей был закрыт.'],
  ['weather', 'погода', 'n', 'What’s the *weather* like today?', 'Какая сегодня погода?', { note: 'Неисчисляемое: не a weather. What’s the weather like?', rule: 'countable' }],
  ['worried', 'обеспокоенный, волнующийся', 'adj', 'I’m *worried* about my exam.', 'Я волнуюсь из-за экзамена.', { note: 'worried ABOUT.', rule: 'dep-prep' }],
  ['achieve', 'достигать', 'v', 'She *achieved* her goal of running a marathon.', 'Она достигла своей цели — пробежала марафон.'],
  ['argue', 'спорить, ругаться', 'v', 'My brother and I often *argue* about politics.', 'Мы с братом часто спорим о политике.', { note: 'argue WITH someone ABOUT something.' }],
  ['attitude', 'отношение (к чему-то)', 'n', 'He has a positive *attitude* to work.', 'У него позитивное отношение к работе.'],
  ['behave', 'вести себя', 'v', 'The children *behaved* very well today.', 'Дети сегодня вели себя очень хорошо.'],
  ['bill', 'счёт (в ресторане, за услуги)', 'n', 'Could we have the *bill*, please?', 'Можно нам счёт, пожалуйста?', { note: 'В американском английском в ресторане — check.' }],
  ['complain', 'жаловаться', 'v', 'He always *complains* about the food.', 'Он вечно жалуется на еду.', { note: 'complain ABOUT something, TO someone.', rule: 'dep-prep' }],
  ['convenient', 'удобный (по времени, месту)', 'adj', 'Is Monday *convenient* for you?', 'Вам удобно в понедельник?', { note: 'Удобный диван — comfortable, а не convenient.' }],
  ['cancel', 'отменять', 'v', 'Our flight was *cancelled* because of the storm.', 'Наш рейс отменили из-за шторма.', { alt: ['canceled'] }],
  ['customer', 'покупатель, клиент', 'n', 'The shop was full of *customers*.', 'В магазине было полно покупателей.'],
  ['deliver', 'доставлять', 'v', 'They’ll *deliver* the sofa on Tuesday.', 'Диван доставят во вторник.'],
  ['describe', 'описывать', 'v', 'Can you *describe* the man you saw?', 'Можете описать мужчину, которого вы видели?', { note: 'describe something TO someone (не describe me).', rule: 'say-tell' }],
  ['environment', 'окружающая среда; обстановка', 'n', 'We must protect the *environment*.', 'Мы должны защищать окружающую среду.'],
  ['experience', 'опыт; случай, впечатление', 'n', 'Do you have any *experience* of working with children?', 'У вас есть опыт работы с детьми?'],
  ['fault', 'вина', 'n', 'Don’t blame me. It’s not my *fault*!', 'Не вини меня. Это не моя вина!'],
  ['forgive', 'прощать', 'v', 'Please *forgive* me for being late.', 'Пожалуйста, прости, что я опоздал.'],
  ['goal', 'цель', 'n', 'My *goal* is to speak English fluently.', 'Моя цель — свободно говорить по-английски.'],
  ['ignore', 'игнорировать, не обращать внимания', 'v', 'Just *ignore* him, he’s in a bad mood.', 'Просто не обращай на него внимания, он не в духе.'],
  ['lazy', 'ленивый', 'adj', 'I was too *lazy* to cook, so we ordered pizza.', 'Мне было лень готовить, и мы заказали пиццу.'],
  ['lonely', 'одинокий (о чувстве)', 'adj', 'She feels *lonely* since her kids moved out.', 'Ей одиноко с тех пор, как дети съехали.', { note: 'alone — один (факт), lonely — одиноко (чувство).' }],
  ['nervous', 'нервничающий, волнующийся', 'adj', 'I always get *nervous* before interviews.', 'Я всегда нервничаю перед собеседованиями.'],
  ['offer', 'предлагать (дать или сделать)', 'v', 'He *offered* to help me with my bags.', 'Он предложил помочь мне с сумками.', { note: 'offer + to do. Предложить идею — suggest.', rule: 'verb-patterns' }],
  ['patient', 'терпеливый; пациент', 'adj', 'Be *patient*, the doctor will see you soon.', 'Потерпите, врач скоро вас примет.'],
  ['proud', 'гордый, гордящийся', 'adj', 'I’m so *proud* of you!', 'Я так тобой горжусь!', { note: 'proud OF.', rule: 'dep-prep' }],
  ['rude', 'грубый, невежливый', 'adj', 'It’s *rude* to interrupt people.', 'Перебивать людей невежливо.'],
  ['several', 'несколько', 'det', 'I’ve been to Paris *several* times.', 'Я был в Париже несколько раз.'],
  ['solve', 'решать (проблему, задачу)', 'v', 'We need to *solve* this problem quickly.', 'Нам нужно быстро решить эту проблему.', { note: 'solve a problem, но decide what to do.' }],
  ['staff', 'персонал, сотрудники', 'n', 'The hotel *staff* were very helpful.', 'Персонал отеля был очень услужливым.'],
  ['tidy', 'аккуратный, прибранный; убирать', 'adj', 'Please keep your room *tidy*.', 'Пожалуйста, поддерживай порядок в комнате.', { note: 'tidy up — прибраться.' }],
  ['valuable', 'ценный', 'adj', 'Thanks for the *valuable* advice.', 'Спасибо за ценный совет.'],
  ['waste', 'тратить впустую; отходы', 'v', 'Don’t *waste* your time on that.', 'Не трать на это время.'],
  ['wonder', 'интересоваться, задаваться вопросом', 'v', 'I *wonder* what time it is.', 'Интересно, который час.', { note: 'После I wonder — прямой порядок слов.', rule: 'questions' }],
  ['abroad', 'за границей, за границу', 'adv', 'Have you ever lived *abroad*?', 'Ты когда-нибудь жил за границей?', { note: 'Без предлога: go abroad (не go to abroad).' }],
  ['accommodation', 'жильё, размещение', 'n', 'The price includes *accommodation* and breakfast.', 'В цену входит проживание и завтрак.', { note: 'В британском английском неисчисляемое.', rule: 'countable' }],
  ['apologise', 'извиняться', 'v', 'He *apologised* for being late.', 'Он извинился за опоздание.', { alt: ['apologize'], note: 'apologise FOR something, TO someone.', rule: 'dep-prep' }],
  ['brave', 'храбрый', 'adj', 'It was very *brave* of you to say that.', 'С твоей стороны было очень смело это сказать.'],
  ['confident', 'уверенный (в себе)', 'adj', 'I feel more *confident* speaking English now.', 'Теперь я увереннее говорю по-английски.'],
  ['equipment', 'оборудование, снаряжение', 'n', 'Do we need any special *equipment*?', 'Нам нужно какое-то специальное снаряжение?', { note: 'Неисчисляемое: без -s и без an.', rule: 'countable' }],
  ['furniture', 'мебель', 'n', 'We need to buy some new *furniture*.', 'Нам нужно купить новую мебель.', { note: 'Неисчисляемое: a piece of furniture — предмет мебели.', rule: 'countable' }],
  ['salary', 'зарплата (оклад)', 'n', 'The job has a good *salary*.', 'На этой работе хорошая зарплата.'],
  ['skill', 'навык, умение', 'n', 'Communication *skills* are important in any job.', 'Навыки общения важны на любой работе.'],
  ['prepare', 'готовить(ся)', 'v', 'I need to *prepare* for tomorrow’s meeting.', 'Мне нужно подготовиться к завтрашней встрече.', { note: 'prepare FOR something.' }],
  ['frightened', 'испуганный', 'adj', 'The child was *frightened* of the dark.', 'Ребёнок боялся темноты.', { note: 'frightened OF.', rule: 'dep-prep' }],
  ['generous', 'щедрый', 'adj', 'It’s very *generous* of you to pay for dinner.', 'Очень щедро с твоей стороны оплатить ужин.'],
  ['honest', 'честный', 'adj', 'To be *honest*, I didn’t like the film.', 'Честно говоря, фильм мне не понравился.', { note: 'h не читается: an honest man.' }],
  ['mess', 'беспорядок, бардак', 'n', 'Sorry about the *mess*, we’re moving house.', 'Извините за беспорядок, мы переезжаем.'],
  ['noisy', 'шумный', 'adj', 'Our street is very *noisy* at night.', 'Ночью на нашей улице очень шумно.'],
  ['shy', 'застенчивый', 'adj', 'He was too *shy* to ask her to dance.', 'Он был слишком застенчив, чтобы пригласить её на танец.'],
  ['magazine', 'журнал', 'n', 'I read an interesting article in a *magazine*.', 'Я прочитал интересную статью в журнале.', { note: 'Магазин — shop или store.', rule: 'false-friends' }],
  ['look after', 'заботиться, присматривать', 'phr v', 'Can you *look after* my cat while I’m away?', 'Можешь присмотреть за моим котом, пока меня нет?'],
  ['give up', 'бросить (привычку), сдаться', 'phr v', 'My dad *gave up* smoking last year.', 'Мой папа бросил курить в прошлом году.', { note: 'give up + -ing.', rule: 'verb-patterns' }],
  ['find out', 'узнать, выяснить', 'phr v', 'I need to *find out* when the train leaves.', 'Мне нужно выяснить, когда отходит поезд.'],
  ['get on with', 'ладить с кем-то', 'phr v', 'Do you *get on with* your colleagues?', 'Ты ладишь с коллегами?'],
  ['look forward to', 'с нетерпением ждать', 'phr v', 'I’m *looking forward to* the holidays.', 'Я с нетерпением жду каникул.', { note: 'look forward to + -ing: I look forward to hearing from you.', rule: 'to-preposition' }],
  ['run out of', 'закончиться (о запасе)', 'phr v', 'We’ve *run out of* milk.', 'У нас закончилось молоко.'],
  ['put off', 'откладывать', 'phr v', 'Stop *putting off* your homework!', 'Хватит откладывать домашнее задание!', { note: 'put off + -ing.' }],
  ['turn down', 'отклонить (предложение); убавить', 'phr v', 'She *turned down* the job offer.', 'Она отказалась от предложения о работе.'],
  ['pick up', 'забрать (кого-то); поднять', 'phr v', 'I’ll *pick* you *up* at the airport.', 'Я заберу тебя из аэропорта.', { note: 'Местоимение ставится между частями: pick you up.' }],
  ['set off', 'отправиться (в путь)', 'phr v', 'We *set off* early in the morning.', 'Мы отправились в путь рано утром.'],
];

export const WORDS_B1 = buildVocab('B1', 'word', ROWS);
